### ISSUE TITLE
R Programming -The basics of programming in R  - Not available

### ISSUE THREAD

**Issue by Rjsiii** [swirldev/swirl_courses#104]
Hey all,  

I'm still new to this whole world so first thanks for all the work getting this created! I love the concept and am excited to get started.   I'll try and manually install this course, but i wanted to make sure someone was aware that it's not available via Swirl's automated installation.  Below is the message i got after following the prompts.

>| To begin, you must install a course. I can install a course for you from the internet, or I can send >you to a web page
>| (https://github.com/swirldev/swirl_courses) which will provide course options and directions for >installing courses
>| yourself. (If you are not connected to the internet, type 0 to exit.)
>
>1: R Programming: The basics of programming in R
>2: Regression Models: The basics of regression modeling in R
>3: Don't install anything for me. I'll do it myself.
>
>Selection: 1
>
>| Sorry, but I'm unable to fetch <U+0091>R Programming: The basics of programming in >R<U+0092> right now. Are you sure you have an
>| internet connection? If so, would you like to try again or visit the course repository for instructions on >how to install
>| a course manually? Type 0 to exit.>

**Comment by WilCrofter** [comment]
Try one or both of the following
```
library(swirl)
install_from_swirl("R Programming")
```

```
library(swirl)
install_from_swirl("R Programming", mirror="bitbucket")
```

**Comment by seankross** [comment]
Closing this issue, @Rjsiii please get in touch if you still need help.
