### ISSUE TITLE
Help with functions?

### ISSUE THREAD

**Issue by kiwi1683** [swirldev/swirl_courses#105]
It would be great to have a course on functions. I've attempted the R Programming course on Coursera twice, but I just have trouble making the leap from the videos to the first assignment. It would be excellent to have optional assignments or a swirl module to work through these much more in depth.

**Comment by seankross** [comment]
There will be a functions course as part of R Programming next week, with more to follow.

**Comment by seankross** [comment]
A functions lesson was added in #46.
