### ISSUE TITLE
dplyr no longer prints all rows if there are fewer than 100, now the threshold is 20

### ISSUE THREAD

**Issue by ekuns** [swirldev/swirl_courses#113]
In the second swirl class of Getting_and_Cleaning_Data (Grouping_and_Chaining_with_dplyr) at the 47% mark, you are told to enter `top_counts` and you then see the comment:

    | Hey, that's the first time we've seen more than the first 10 rows of our data! By default, if the
    | dataset you're working with has more than 100 rows, dplyr will only print the first 10. Otherwise, it
    | will print all rows, since it's not as overwhelming.

As of a commit to dplyr from October 2014, that is no longer true:

* Complaint:  https://groups.google.com/forum/#!topic/manipulatr/zG0p0eZH5z8
* Ticket:  https://github.com/hadley/dplyr/issues/710
* Commit:  https://github.com/hadley/dplyr/commit/b006f829e305d10e3b411c5841511ff24de49c33

The threshold is now 20, not 100.  This changes the text of this answer as well as the next text:

    | In this case, there are 61 packages in our top 1%, so dplyr has printed all of them. If we only want
    | to see the first 20, we can use the head function like so: head(top_counts, 20).

and finally, this also impacts the text at 55%:

    | ...And if you keep on going, you'll see swirl at number 43, with 820 total downloads. Sweet!

as you no longer see the 43rd entry in the output.  The same is true for the output at 68%:

    | Now Rcpp is in the lead, followed by stringr, digest, plyr, and ggplot2. swirl moved up a few spaces
    | to number 40, with 698 unique downloads. Nice!

It may impact some of the thresholds chosen in the R code, such as countries > 60, in following examples, where you now only see the top 10 of the 46 results, if the intention was that you would see all results in this output.

Again, the text at 87% refers to an entry that is no longer visible:

    | It looks like Rcpp is on top with downloads from 84 different countries, followed by digest, stringr,
    | plyr, and ggplot2. swirl jumped up the rankings again, this time to 27th.

**Comment by ncarchedi** [comment]
This is really helpful, thanks. I haven't had a chance to update the course since dplyr 0.4.0 came out on Jan 9, but will try to get to it this weekend.

**Comment by ncarchedi** [comment]
Fixed in 30d4aec98b9021a155ef931c8d04190db85e64a0. Please let me know if I missed anything. Thanks again.
