### ISSUE TITLE
Getting and Cleaning Data, Tidying Data with tidyr - requiring use of deprecated function at 87%.

### ISSUE THREAD

**Issue by tbukic** [swirldev/swirl_courses#114]
Task text on 87%:

>|================================================================          |  87%
>
>| Now, pass as arguments the passed and failed tables (in order) to the dplyr function rbind_list() >(for 'row bind'),
>| which will join them together into a single unit. Check ?rbind_list if you need help.

From help:

>Deprecated functions
>
>rbind_list and rbind_all have been deprecated. Instead use bind_rows.

I think text should be changed to suggest using of <addr>bind_rows()</addr>  instead of <addr>rbind_list()</addr>. Both produce the same result, and <addr>bind_rows()</addr> is clearly deprecated.

Best regards!

**Comment by ncarchedi** [comment]
@tbukic Thanks, I'll update this to reflect dplyr 0.4.0.

**Comment by ncarchedi** [comment]
Fixed in commit 2ffdf376240566a1e072cc703e4179c8b9325a1f. Please let me know if I missed anything.
