### ISSUE TITLE
Em Dash in sat13 causing unicode errors on some systems

### ISSUE THREAD

**Issue by thoughtfulbloke** [swirldev/swirl_courses#116]
Hello,

Cell [2,1] in Getting and Cleaning/ Tidying with tidyr/ sat13.csv has an Em Dash between the 700 and 800, unlike the other entries that use a standard hyphen. This is causing unicode issues for some people, such as in https://class.coursera.org/getdata-010/forum/thread?thread_id=98

This is being solved on an individual basis by replacing the Em Dash with a hyphen, so it is 700-800 rather than the original 700–800, but I was wondering if it might be possible to replace it at the original source file. I'm not familiar enough with the code to quickly know it there are other implications, so thought I'd mark it as an issue rather than do a pull request.

**Comment by ncarchedi** [comment]
Thanks a lot for pointing this out. Just made the fix a3a89646aa6f14628101ab82fb0eb62fc4a30104, but you'll need to reinstall the course with `install_from_swirl("Getting and Cleaning Data")`.
