### ISSUE TITLE
swirl 2.2.21: R Programming, Workspace and Files, Provide the full path to the file "mytest3.R" : misleading wording

### ISSUE THREAD

**Issue by marko-p** [swirldev/swirl_courses#127]
The question asks me to output the full path to the file, but actually expects the relative path as a correct answer.

Search for the full file path directed me to use the normalizePath() function, which indeed outputted the full path to the file. However, I got the "Almost! Try again." message and a tip to use file.path("mytest3.R") instead. File.path() returned the relative path to the file and i got encouraging words that I'm on the right path again :)

``` splus
| Provide the full path to the file "mytest3.R".

> normalizePath("mytest3.R")
[1] "/wd/swirl/testdir/mytest3.R"

| Almost! Try again. Or, type info() for more options.

| file.path("mytest3.R") works.

> file.path("mytest3.R")
[1] "mytest3.R"

| That's the answer I was looking for.
```

**Comment by seankross** [comment]
I see what you mean. We'll consider changing the wording of this question.

**Comment by seankross** [comment]
I changed the wording of this question in 2d15c5f85d850cc8d7a1c1b80869921b06339483 so I'm closing this issue.
