### ISSUE TITLE
Problem working with dates in different local language then English

### ISSUE THREAD

**Issue by jfneis** [swirldev/swirl_courses#132]
Hello everyone,

In Lesson 13, Dates and Times, when converting a date using strptime, swirl will accept the answer with "October 17, 1986 08:24", but depending on the user locale it will generate an NA time object.

```R
> t4 <- strptime(t3, "%B %d, %Y %H:%M")
| You are really on a roll!
 |==========================================================================================================================                               |  80%
| Print the contents of t4.
> t4
[1] NA
```

Somehow the system should get the system´s local date and time formats to formulate its given directions and evaluated answers.

**Comment by seankross** [comment]
This issue is currently under active discussion [here](https://github.com/swirldev/swirl_courses/pull/50), so I'm closing this issue.
