### ISSUE TITLE
Data Analysis Typo

### ISSUE THREAD

**Issue by zleamy** [swirldev/swirl_courses#135]
Not sure where to leave this comment... I'm relatively new to github. Anyway, I thought I'd point out a typo in the data analysis lesson in the part on central tendency (mode). I've made the appropriate change in caps and quotes.

"Finally, we may be most interested in finding the value that shows up the most in our dataset. In
| other words, what "IS" the most common value in our dataset? This is called the MODE and it is found..."

Also, I love this in-console teaching. Well done.

**Comment by seankross** [comment]
Thanks. I'll make this change shortly.
