### ISSUE TITLE
filter() error

### ISSUE THREAD

**Issue by rwhewell** [swirldev/swirl_courses#137]
Keep getting error with filter(). Not able to get beyond this step in the swirl course. See below for error statement:

| You can specify as many conditions as you want, separated by commas. For example
| filter(cran, r_version == "3.1.1", country == "US") will return all rows of cran
| corresponding to downloads from users in the US running R version 3.1.1. Try it
| out.

> skip()

| Entering the following correct answer for you...

> filter(cran, r_version == "3.1.1", country == "US")
Error in eval(expr, envir, enclos) : 
  could not find function "any_of_exprs"

| Leaving swirl now. Type swirl() to resume.

**Comment by ncarchedi** [comment]
You are running an old version of swirl. Please update and try again.

**Comment by rwhewell** [comment]
I installed it yesterday. Is there a way to uninstall and reinstall? is
there a way to select a newer version of swirl through the install.packages
in rstudio?

thanks for you help.......RIck

**Comment by rwhewell** [comment]
I just reinstalled and am running now. I think it is working fine now.
Thanks.
