### ISSUE TITLE
Problem installing EDA

### ISSUE THREAD

**Issue by seankross** [swirldev/swirl_courses#140]
From @gauravksrivastava

> Using R Studio Version 0.98.1091 on OS X 10.10

> Both install_from_swirl("Exploratory_Data_Analysis") and install_from_swirl("Exploratory Data Analysis") hang and the course does not get installed.

> And, efforts to install from github are not yielding (as illustrated below) too.

```
install_course_github("reginaastri","Exploratory_Data_Analysis", multi=TRUE)
Error in unzip(path, list = TRUE) : 
zip file '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/swirl/Courses/temp.zip' cannot be opened
install_course_github("reginaastri","Exploratory Data Analysis", multi=TRUE)
Error in unzip(path, list = TRUE) : 
zip file '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/swirl/Courses/temp.zip' cannot be opened
```
> Any pointers?

**Comment by seankross** [comment]
I suggest you try the following:

1. Download the swirl course repository zip from [this link](https://github.com/swirldev/swirl_courses/archive/master.zip).
2. Install the course with:
 
```
install_course_zip("path/to/zip/swirl_courses-master.zip", multi = TRUE, which_course = "Exploratory_Data_Analysis")
```

**Comment by WilCrofter** [comment]
Just a remark: EDA took a while to install_from_swirl when I tried it just now.

Also,
```
install_course_github("reginaastri","Exploratory_Data_Analysis", multi=TRUE)
```
can't work since there is [no such course at reginaastri](https://github.com/reginaastri?tab=repositories).

**Comment by gauravksrivastava** [comment]
Thanks, Sean and William!

 install_from_swirl did take a while but ultimately installed the course.
