### ISSUE TITLE
Unable to install course "R programming" from swirl() menu

### ISSUE THREAD

**Issue by madhavin** [swirldev/swirl_courses#142]
Hi,
 Am a newbie to Swirl. I am taking a course "R Programming" on Coursera and my instructor asked us to try Swirl. I am unable to install the course though.. Please see the issue in this attachment..

![unable_to_install_r_programming_via_swirl](https://cloud.githubusercontent.com/assets/11020804/6448906/f4984104-c0d1-11e4-8f02-c80745b97bce.JPG)

**Comment by seankross** [comment]
Hi @madhavin,

Please try the following:

```
library(swirl)
uninstall_all_courses()
install_from_swirl("R_Programming")
```

Let me know if that works.

**Comment by madhavin** [comment]
Hi @seankross,
  Thank you for the note. Previously I tried to use the swirl() dialog.

Now after following your instructions I could install the course but with an error message during the uninstall.. 

![install_after_uninstall](https://cloud.githubusercontent.com/assets/11020804/6450107/68dfee1a-c0da-11e4-8c9d-865fb6b6afca.JPG)

**Comment by seankross** [comment]
Hi @madhavin,

Are you able to do the R Programming course? If so you should be good to go!

**Comment by madhavin** [comment]
Am able to do the course now.
Thank you,
Madhavi

**Comment by madhavin** [comment]
Can I please suggest to the Swirl community to include some form of communication while we choose to install the courses? It helps to know something is in progress instead of a blank wait time. That would avoid abrupt end of installation by the user suspecting that nothing is happening.
Regards,
Madhavi

**Comment by seankross** [comment]
Hi @madhavin, 

Thanks for the feedback. We've discussed this before in #115 and it would be a good feature.

**Comment by sagarthatte** [comment]
I faced the same issue while accessing swirl courses. Thanks @madhavin  and @seankross  for the help. :)

**Comment by githubenny** [comment]
Nothing happens to indicate that course was installed successfully after going through the sequence of commands listed above. As you can see there is no prompt afterwards.

 I'm on Windows 7 64 Bit OS.

![r_swirl](https://cloud.githubusercontent.com/assets/10855239/6550000/0c433634-c5db-11e4-8d84-3bc5482ed372.jpg)

**Comment by madhavin** [comment]
Hi Benjamin,
  I used Rstudio on Windows XP SP3. It took me a while (atleast 5min)  for the R programming course to install after doing an uninstall. Could you please see if it is the same for you ?
Regards,
Madhavi

**Comment by githubenny** [comment]
Yes it took a few minutes but it finally resolved itself.

**Comment by annrosebright** [comment]
Hi ....am trying to install the same course... but for me even after using the new command the error is as follows : >  


> library(swirl)
> uninstall_all_courses()
All courses uninstalled successfully!
> install_from_swirl("R_Programming") 
Error in unzip(path, list = TRUE) : 'exdir' does not exist
> swirl()


Pls help....

**Comment by seankross** [comment]
@annrosebright Try uninstalling and then reinstalling swirl.

**Comment by SUMIT0206** [comment]
> install_from_swirl("Getting and Cleaning Data")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name
GETTING THIS ERROR

**Comment by seankross** [comment]
@SUMIT0206 try: `install_course("Getting and Cleaning Data")`

**Comment by SUMIT0206** [comment]
thanks seankroos

**Comment by SUMIT0206** [comment]
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'C:/Users/Admin/Documents/R/win-library/3.3/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/2014-07-08.csv': No such file or directory

**Comment by demidimatera** [comment]
Hi, I already installed swirl but I kept receiving these errors, what shall I do?

> install.packages("swirl")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/swirl_2.4.3.zip'
Content type 'application/zip' length 236386 bytes (230 KB)
downloaded 230 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\ddimatera\AppData\Local\Temp\Rtmpkxg3yV\downloaded_packages
> library(swirl)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
In addition: Warning message:
package ‘swirl’ was built under R version 3.3.3 
Error: package or namespace load failed for ‘swirl’
> install_course("R Programming")
Error: could not find function "install_course"

**Comment by seankross** [comment]
See https://github.com/swirldev/swirl/issues/628#issuecomment-316138820

**Comment by kathyaustin70** [comment]
Hi,  I'm getting a slightly different type of error before and after I try to use the fix
> library(swirl)
> uninstall_all_courses()

| Are you sure you want to uninstall all swirl courses? This
| will delete all of the contents of your swirl course
| directory.

1: Yes
2: No

Selection: 1
All courses uninstalled successfully!
> install_from_swirl("R_Programming")
Error in loadNamespace(name) : there is no package called ‘curl’

**Comment by kathyaustin70** [comment]
I found the answer from the above, I had to install curl
install.packages("curl")

**Comment by jayashreek-1504** [comment]
Hi,
Iam getting this error.
> install_course("The R Programming Environment")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to swirlstats.com port 80: Timed out
> uninstall_all_courses()

| Are you sure you want to uninstall all swirl courses? This will delete all of the contents of your swirl course directory.
All courses uninstalled successfully!
> install_course("The R Programming Environment")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to swirlstats.com port 80: Timed out
I tried uninstalling courses, and install again.  Still im having the same issue
> uninstall_all_courses()
| Are you sure you want to uninstall all swirl courses? This will delete all of the contents of your swirl course directory.
All courses uninstalled successfully!
> install_course("The R Programming Environment")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to swirlstats.com port 80: Timed out
