### ISSUE TITLE
Mathematical Biostatistics Boot Camp course

### ISSUE THREAD

**Issue by msahebhonar** [swirldev/swirl_courses#143]
In "Mathematical Biostatistics Boot Camp" course part 3 "Errors Power and Sample Size" I think this sentence needs to be modified.  
original:
"Since the type II error rate is the probability of <strong>INCORRECTLY rejecting the null hypothesis</strong> and power is the probability of CORRECTLY rejecting the null hypothesis, power is therefore equal to one minus the type II error rate"

Modified:
"Since the type II error rate is the probability of <strong>INCORRECTLY fail to reject the null hypothesis</strong> and power is the probability of CORRECTLY rejecting the null hypothesis, power is therefore equal to one minus the type II error rate"

Thank you

**Comment by seankross** [comment]
I'll investigate this. Thanks.

**Comment by seankross** [comment]
Changed in df512b2. Thanks for the heads up!
