### ISSUE TITLE
Back to the basement

### ISSUE THREAD

**Issue by mak600d** [swirldev/swirl_courses#171]
Dear Sir or Madam, 
my name is Ihor Mak and I have a little problem. In my first session in swirl i have unintentionally chosen Regression Models instead Basics. And now I can not back to the main menu with this lesson. What can I do?
Best regards,
Ihor Mak

**Comment by ncarchedi** [comment]
Type `main()` to go back to the main menu. If you want to install the R Programming course, you can exit swirl and type `install_from_swirl("R Programming")`. Then restart swirl and you'll see it in the course menu.

**Comment by mak600d** [comment]
Thank you!

**Comment by ncarchedi** [comment]
No problem :)
