### ISSUE TITLE
Problem with slides to be viewed "locally."

### ISSUE THREAD

**Issue by gianbalsamo** [swirldev/swirl_courses#173]
I like Swirl and have gone through several of its courses. But I wonder if I do something wrong or some of these courses are incomplete. For instance, when I start Regression_Models, I am told that slides for this course may be found at github https://github.com/DataScienceSpecialization/courses, and the first lesson
corresponds to Regression_Models/01_03_ols. When I go there I find a few graphs, but none of what, at 23% of the lesson, is referred to as “shown algebraically in the slides.” Hence, it’s difficult to follow the lesson’s argument. I’ve gone though several Swirl courses, and have never managed to get much help from the slides I was supposed to “view locally.” Any idea of what’s wrong or what I may be doing wrong? Thanks.

**Comment by WilCrofter** [comment]
The slides are nicely organized at [http://datasciencespecialization.github.io/](http://datasciencespecialization.github.io/)

**Comment by gianbalsamo** [comment]
Thanks so much.
