### ISSUE TITLE
Unable to load "Grouping and Chaining with dplyr" in Getting and Cleaning Data

### ISSUE THREAD

**Issue by Jake9** [swirldev/swirl_courses#174]
Hi,

After I installed Getting and Cleaning Data and I tried to load 2nd lesson "Grouping and Chaining with dplyr", this error message appears: 

Selection: 2

| Attemping to load lesson dependencies...

| Package ‘dplyr’ loaded correctly!

Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

| Leaving swirl now. Type swirl() to resume.

May anyone help ?

Thanks a lot
Jake

**Comment by ncarchedi** [comment]
I think you may be running an old version of swirl. Let us know if reinstalling helps.

**Comment by Jake9** [comment]
Thanks for your reply, after I upgraded the R, it works now.
