### ISSUE TITLE
R programming functions lesson - instructions for the Vi editor

### ISSUE THREAD

**Issue by ofcoursera** [swirldev/swirl_courses#184]
Hi, I have been using Swirl as part of the Coursera R programming course and have found it very useful. 

I encountered a bit of a stumbling block for some of the lessons, e.g. functions 
where I ended up in the Vi editor and couldn't work out how to enter responses to questions or even to exit. 

Amending my default editor for R didn't help either, as the code to be amended didn't then display.
Would it be possible to add a few lines to the instructions for Vi commands necessary to complete the exercises? 

Are there other editors that would work?
[I'm working on Ubuntu Trusty Tahr 14.04. Gedit is my default text editor for other applications, R version 3.2.1 (2015-06-18) -- "World-Famous Astronaut"]

**Comment by seankross** [comment]
Check out this guide: https://kb.iu.edu/d/acnc If you're unfamiliar with Vim or Emacs, I suggest you use Nano as a text editor.

**Comment by ofcoursera** [comment]
Thank you very much for your response, I will take a look at Nano.
