### ISSUE TITLE
Accept shorthand boolean values in responses

### ISSUE THREAD

**Issue by duxan** [swirldev/swirl_courses#185]
Hi, I have noticed that in lessons from "R programming" and "Getting and Cleaning Data" courses, responses in which I use `T` or `F` for `TRUE` or `FALSE`, the answer is not accepted.

Is there some systematic way to modify source code so that both variants can be accepted or is it only up to course instructor to implement it?

**Comment by seankross** [comment]
See swirldev/swirl#268

**Comment by duxan** [comment]
Tnx!
