### ISSUE TITLE
EDA, unit #4, ggplot2, qplot

### ISSUE THREAD

**Issue by cnew4342** [swirldev/swirl_courses#187]
Posted on Coursera discussion forum:

Look at this please, the qplot thickens!  Back to swirl, attempting the qplot with same result, then I simply rerun the same qplot command & it works!  I get the result in the plot window but I am no longer in swirl, it just dropped away.  BTW, I'm in Mac OS X 10.9.5

| Oh, there are 38 models. We're interested in the effect engine displacement (displ) has on highway gas mileage (hwy), so we'll use the ggplot2 command qplot to display this relationship. Run qplot now with
| three arguments. The first two are the variables displ and hwy we want to plot, and the third is the argument data set equal to mpg. As before, this allows us to avoid using the mpg$variable notation for
| the first two arguments.

> qplot(displ, hwy, data = mpg)
Error in (function (expr, val, ok, vis, data = e)  : 
  object 'PANEL' not found
> qplot(displ, hwy, data = mpg)
>

**Comment by tarajano** [comment]
Hello,
Same issue for me. 
Did you find a solution? 
Thanks and best, 
M

**Comment by cnew4342** [comment]
Y'know, it's several months since I dealt with the issue.  I believe I did
find a solution but it just came about by fiddling around with it & I can't
seem to remember anything more specific.  Sorry.

On Tue, Jan 12, 2016 at 2:18 PM, Manuel Alonso <notifications@github.com>
wrote:

> Hello,
> Same issue for me.
> Did you find a solution?
> Thanks and best,
> M
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swirldev/swirl_courses/issues/187#issuecomment-171021481>
> .
>



-- 
Carl F. Newman
3130 Wisconsin Ave NW
Apt. #311
Washington, DC 20016
202-237-1771

Labor wants pride and joy in doing good work, a sense of making or doing
something beautiful or useful - to be treated with dignity and respect as
brother and sister.
<http://www.brainyquote.com/quotes/quotes/t/thorsteinv401558.html>
Thorstein Veblen
<http://www.brainyquote.com/quotes/quotes/t/thorsteinv401558.html>




<https://www.facebook.com/#>

**Comment by seankross** [comment]
@tarajano see #189 and let me know if that works.

**Comment by tarajano** [comment]
Hi @seankross , thanks for replying..
I was using R.app for OS X and I just moved to iTerm (command terminal) and all OK now. 
best

**Comment by seankross** [comment]
Okay, good to know. Going to close this issue.
