### ISSUE TITLE
object 'PANEL' not found in Exploratory Data Analysis, Plotting Systems

### ISSUE THREAD

**Issue by Jake9** [swirldev/swirl_courses#189]
When I am doing this question (75% of the course):

| Oh, there are 38 models. We're interested in the effect engine displacement (displ) has on highway gas mileage (hwy), so we'll use
| the ggplot2 command qplot to display this relationship. Run qplot now with three arguments. The first two are the variables displ and
| hwy we want to plot, and the third is the argument data set equal to mpg. As before, this allows us to avoid using the mpg$variable
| notation for the first two arguments.

> qplot(displ, hwy, data = mpg)
Error in (function (expr, val, ok, vis, data = e)  : 
  object 'PANEL' not found

It keeps on saying "object 'PANEL' not found" and prevents me from moving on.

any idea on how to solve it ?

Thanks very much
Jake

**Comment by seankross** [comment]
Can you include a screenshot of this error? Thanks.

**Comment by Jake9** [comment]
![screen shot 2015-07-07 at 9 19 03 am](https://cloud.githubusercontent.com/assets/4312048/8536851/58b49cbc-2489-11e5-84fc-6504014018ad.png)

Hi Sean,

Here is the screenshot attached.

Thanks
Jake

**Comment by seankross** [comment]
I hate to say this, but I would recommend restarting this lesson. Let me know if that resolves the problem.

**Comment by Jake9** [comment]
Hi Sean,

it seems that this issue is related to ggplot2.

As I can complete 5: Base Plotting System, 6: Lattice Plotting System and 7: Working with Colors, but when I move on to 8: GGPlot2 Part1, the same problem that I encountered in 4: Plotting Systems happened again.

Pls see the screenshot attached.
![screen shot 2015-07-10 at 10 36 44 am](https://cloud.githubusercontent.com/assets/4312048/8611235/5b7723d4-26f0-11e5-9ad5-0838f6a6e623.png)


R version I use is R 3.2.0 GUI 1.65 Mavericks build (6931

Any ideas on how to solve it ?

Thanks again
Jake

**Comment by Jake9** [comment]
The strange thing is: this error just kicked me out of Swirl  ...

**Comment by seankross** [comment]
Can you get the newest version of R? Also do you have the newest ggplot2?

**Comment by Jake9** [comment]
Hi, I tried to do this on Rstudio, and it works now :) Thanks Sean.

**Comment by seankross** [comment]
Good to know. Sorry that was a hassle.

**Comment by JMaggieZhang** [comment]
I have the same problem!

**Comment by sanirudh27** [comment]
Even i am facing the same problem. Is there a solution to it ?

**Comment by sanirudh27** [comment]
Thanks for the Solution. It works perfectly in RStudio and not in R.. THis is weird, but ya temp solution is found out ! ..  

Thanks !

**Comment by MaiseB** [comment]
I have had the exact same issue. This now works on R studio. 
<img width="1440" alt="screen shot 2016-05-04 at 15 53 16" src="https://cloud.githubusercontent.com/assets/16984219/15018176/6fe26e1c-1210-11e6-9ddd-8e7c621dbc58.png">

**Comment by apjanke** [comment]
FYI, I'm seeing the same error in R.app 3.3.1 with ggplot 2.1.0 on OS X. Switching to RStudio on the same machine and R version got it to work.

**Comment by foolishc** [comment]
same here! cannot proceed!
So the solution is to switch to Rstudio?
Mine is the 3.3.2 version on OS 10.10.3

**Comment by seankross** [comment]
@foolishc switching to RStudio should do the trick.
