### ISSUE TITLE
Warning message in Swirl lesson 4

### ISSUE THREAD

**Issue by darenwelsh** [swirldev/swirl_courses#191]
I got a warning message at the 76% mark in Swirl lesson 4. I was able to continue and complete the lesson.

```
warning messages from top-level task callback 'mini'
Warning message:
In stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE) :
  longer object length is not a multiple of shorter object length
```

![screen shot 2015-07-16 at 12 15 50 pm](https://cloud.githubusercontent.com/assets/6728676/8730229/3b14016a-2bb5-11e5-94a1-aa9a23786e85.png)

**Comment by seankross** [comment]
Did this warning cause any interference with the lesson?

**Comment by darenwelsh** [comment]
No

**Comment by seankross** [comment]
Okay, do you mind if I close this issue then? Thanks for letting us know about this warning.

**Comment by darenwelsh** [comment]
So just to clarify, I was able to continue with the lesson, but I would consider the warning a minor intrusion to the lesson. Someone unfamiliar with warning messages might not realize they can continue.

That said, I don't mind. I'm just passing along an anomaly I saw.

**Comment by seankross** [comment]
We appreciate it. I'll see if I can reproduce this, but if I can't I'm just going to close this issue.
