### ISSUE TITLE
Unable to Install all the courses in Windows by downloading Zip file

### ISSUE THREAD

**Issue by skmnc** [swirldev/swirl_courses#192]
unzip(path, list = TRUE) : 
zip file '/Users/Dibs/Downloads/swirl_courses-master.zip' cannot be opened

also file.exists() is returning FALSE

**Comment by seankross** [comment]
If `file.exists()` is returning `FALSE`, then there must be something wrong with the path you provided. Try something like [this](https://technet.microsoft.com/en-us/magazine/ff678296.aspx) to get the full path.

**Comment by skmnc** [comment]
I am using the below to get my file path 
![image](https://cloud.githubusercontent.com/assets/13129151/8855910/5837a46a-3185-11e5-8d1f-e08c58cad8b6.png) and using
 install_course_zip("\\C:\\Users\\Sony\\Downloads\\swirl_courses-master.zip") to install but I am getting
Warning message:
In unzip(path, exdir = file.path(system.file(package = "swirl"),  :
  error 1 in extracting from zip file

**Comment by seankross** [comment]
Try:
```
install_course_zip("C:\Users\Sony\Downloads\swirl_courses-master.zip", multi=TRUE,
                   which_course=c("R Programming", "Data Analysis", "Exploratory Data Analysis", "Getting and Cleaning Data", "Regression Models", "Statistical Inference"))
```

**Comment by skmnc** [comment]
Sir now i am getting another warning message on using
 install_course_zip("C:\\Users\\Sony\\Downloads\\swirl_courses-master.zip", multi=TRUE,which_course=c("R Programming,"Data Analysis","Exploratory Data Analysis","Getting and Cleaning Data","Regression Models","Statistical Inference"))
Error: unexpected symbol in "install_course_zip("C:\\Users\\Sony\\Downloads\\swirl_courses-master.zip", multi=TRUE,which_course=c("R Programming,"Data"

**Comment by skmnc** [comment]
Thanks sir i finally installed the courses

**Comment by seankross** [comment]
Okay great! Let us know if you have any other issues.

**Comment by skmnc** [comment]
Sure sir, I am a begginer on R and I just want to know that how will i be able to expertise in R. I want to ask you that what should I follow?

**Comment by seankross** [comment]
Excuse me for making a assumption, but it seems to me that English is not your first language. What is your native language? I'll try to find you some R guides in that language.

**Comment by skmnc** [comment]
No sir I am quite comfortable with English.

**Comment by seankross** [comment]
The best guides right now (other than swirl :smile:) in my very opinionated opinion are the following (in the order I think you should read them):

1. [R Programming for Data Science](https://leanpub.com/rprogramming)
2. [Exploratory Data Analysis with R](https://leanpub.com/exdata)
3. [Elements of Data Analytic Style](https://leanpub.com/datastyle)
4. [Statistical Inference for Data Science](https://leanpub.com/LittleInferenceBook)

All of those books are free.

**Comment by rajish6** [comment]
According to me, the backslash ("\") needs to be replaced with ("/") i.e. ~/Downloads/course etc. and not ~\Users.
