### ISSUE TITLE
Problem in setting Directory in R_Programming

### ISSUE THREAD

**Issue by krishnaiitd** [swirldev/swirl_courses#193]
In the Coursera course in R programming, while setting directory as ```setwd("./testdir")``` it gives error, it should accept both ```setwd("./testdir")``` & ```setwd("testdir")```

Issue is not in setting the directory to *testdir*, but it is in acceptance of answer.

Attached screenshot is here: 
![swirlissue](https://cloud.githubusercontent.com/assets/1598810/8894080/7afa7ae2-33c7-11e5-9bc6-4685660d04d4.png)

I will submit the pull request tomorrow for this issue.

Thanks
Krishna Prasad

**Comment by ncarchedi** [comment]
Hmm, not sure why you are getting that error. swirl is not producing the error -- R is. Do you have full admin privileges on your computer? This thread may be relevant:

http://r.789695.n4.nabble.com/quot-cannot-change-working-directory-quot-td4492812.html

**Comment by krishnaiitd** [comment]
@ncarchedi Please check this pull request: https://github.com/swirldev/swirl_courses/pull/194, this might be resolve the issue.

**Comment by seankross** [comment]
See my comment in #194

**Comment by latadswapnil** [comment]
Run R-studio as administrator will resolve this issue.

**Comment by negin1986** [comment]
I have the same issue and really can't move to next step. My working directory is changed but swirl does not accept my code. I changed it using setwd("/Users/neginvalizadegan/Desktop/testdir/") but when I try the code that swirl wants, I get error in R. This is how it looks like:

Set your working directory to "testdir" with the setwd() command.

> setwd("/Users/neginvalizadegan/Desktop/testdir/")

| Not quite, but you're learning! Try again. Or, type info() for more options.

| Use setwd("testdir") to set your working directory to "testdir".

> setwd("testdir")
Error in setwd("testdir") : cannot change working directory

**Comment by Eri-Alegre** [comment]
I'm not really sure about how I got here but I want to share what I did, I hope this help to any of you... I wait for your comments to understand better this... wish you luck!!

| Set your working directory to "testdir" with the setwd() command.

> setwd(testdir)
Error in setwd(testdir) : objeto 'testdir' no encontrado
> setwd.testdir()
Error in setwd.testdir() : 
  no se pudo encontrar la función "setwd.testdir"
> 
> info()

| When you are at the R prompt (>):
| -- Typing skip() allows you to skip the current question.
| -- Typing play() lets you experiment with R on your own; swirl will ignore what you do...
| -- UNTIL you type nxt() which will regain swirl's attention.
| -- Typing bye() causes swirl to exit. Your progress will be saved.
| -- Typing main() returns you to swirl's main menu.
| -- Typing info() displays these options again.

> setwd('testdir')
Warning messages:
1: In file(out, "wt") :
  no fue posible abrir el archivo 'C:\Users\FLIARI~1\AppData\Local\Temp\RtmpEVhq0X\Rhttpd23bc36f24074': No such file or directory
2: In file(out, "wt") :
  no fue posible abrir el archivo 'C:\Users\FLIARI~1\AppData\Local\Temp\RtmpEVhq0X\Rhttpd23bc10364e0a': No such file or directory
3: In file(out, "wt") :
  no fue posible abrir el archivo 'C:\Users\FLIARI~1\AppData\Local\Temp\RtmpEVhq0X\Rhttpd23bc7983dc8': No such file or directory

| You got it right!


  |                                                                                                                                                                   
  |============================================================================                                                                                 |  49%
| In general, you will want your working directory to be someplace sensible, perhaps created for the specific project that you are working on. In fact, organizing
| your work in R packages using RStudio is an excellent option. Check out RStudio at http://www.rstudio.com/

**Comment by mariafeiler95** [comment]
It's looking for setwd('testdir') for some reason. Is this a new update or a problem with swirl?
