### ISSUE TITLE
Could not find function "anyNA"

### ISSUE THREAD

**Issue by robertmorrispainter** [swirldev/swirl_courses#198]
R newbie, and I`m not sure what this means or how to fix it.

> install_from_swirl("R Programming")
Error in handle_setopt(h, ...) : could not find function "anyNA"

Thanks.

**Comment by robertmorrispainter** [comment]
I worked it out.

**Comment by seankross** [comment]
How did you solve this?

**Comment by robertmorrispainter** [comment]
Apologies, I was trying to recall, but, I think it was this command.

sudo apt-get install r-base-dev

**Comment by yasaxizm** [comment]
Sorry I just saw the mails.
So…I'm a little confused. Is there anything wrong with the code for Swirl course " R Programming "?

Best
Min
