### ISSUE TITLE
Error in file(con, "r") : invalid 'description' argument when loading courses in swirl 

### ISSUE THREAD

**Issue by had3s** [swirldev/swirl_courses#202]
Hi everyone,

I am kind of new here and I wanted to try the add-on swirl course "R Programming" to the Coursera one. After trying a buch I seemed to have been able to install the swirl course package (via the install_course_zip function as described in the readme file), however, whenever I log into swirl now this happens:

| Please choose a course, or type 0 to exit swirl.

1:   MACOSX
2: swirl courses-master
3: Take me to the swirl course repository!

Selection: 2

| Please choose a lesson, or type 0 to return to course menu.

 1: Data Analysis
 2: ErrFind
 3: Exploratory Data Analysis
 4: Getting and Cleaning Data
 5: Mathematical Biostatistics Boot Camp
 6: Open Intro
 7: R Programming
 8: R Programming Alt
 9: Regression Models
10: Statistical Inference
11: Writing swirl Courses

Selection: 7

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

> 

I don't know what I am doing wrong. Any tip that would help me fix this issue would be much appreciated.

**Comment by seankross** [comment]
Try the following:

```
library(swirl)
uninstall_all_courses()
install_course_zip("path/to/zip/file", multi = TRUE, which_course = "R Programming")
swirl()
```

**Comment by had3s** [comment]
Hi thanks for the quick answer! It is kind of one step forward two steps back. I did what the realm and what you told me and what I got was this:

> install_course_zip("~/Downloads/swirl_courses-master.zip", multi = TRUE, which_course = "R Programming")
Error in install_course_zip("~/Downloads/swirl_courses-master.zip", multi = TRUE,  : 
  Course 'R Programming' not in specified directory. Be careful, course names are case sensitive!

**Comment by seankross** [comment]
Try unzipping `swirl_courses-master.zip` and then use `install_course_directory("~/Downloads/swirl_courses-master/R_Programming")`.

**Comment by had3s** [comment]
Thank you Sean that worked perfectly!

**Comment by seankross** [comment]
That's great to hear. Let us know if you have any other issues.

**Comment by subbro** [comment]
What shall I call you? s

| Please choose a course, or type 0 to exit swirl.

1: functions
2: R Programming
3: working with strings in R
4: Take me to the swirl course repository!

Selection: 3

| Please choose a lesson, or type 0 to return to course menu.

1: stringr

Selection: 1

Error in file(input, encoding = "UTF-8") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

Help appreciated

**Comment by subbro** [comment]
@seankross  can you please take a look at this?

**Comment by wrcstewart** [comment]
same for me
Error in file(input, encoding = "UTF-8") : invalid 'description' argument

**Comment by Chengyang-Hu** [comment]
me to
Error in file(input, encoding = "UTF-8") : invalid 'description' argument
