### ISSUE TITLE
Can't run course, swirl barfs

### ISSUE THREAD

**Issue by asweng** [swirldev/swirl_courses#205]
Should I be reporting this somewhere else?
Here's what I see, in RStudio, after installing and later selecting the course I want to use.  It doesn't seem to matter which lesson (within the course) I choose.  Versions: Rstudio 0.99.473 , R 3.2.2, swirl_2.2.21

1: Data Visualization
2: Take me to the swirl course repository!

Selection: 1

| Please choose a lesson, or type 0 to return to course
| menu.

 1: dependson.txt          2: initLesson.R        
 3: lesson.yaml            4: mod1 boxplot.R      
 5: mod1 dotplot.R         6: mod1 histogram add.R
 7: mod1 histogram.R       8: mod1 leftskew.R     
 9: mod1 rightskew.R      10: mod1 stem.R         
11: mod1 symmetric.R      

Selection: 5

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
What course did you install?

**Comment by asweng** [comment]
Data Visualization.  Sorry if that wasn't evident from my initial post.

**Comment by seankross** [comment]
Try the following:

```r
uninstall_all_courses()
install_from_swirl("Data Analysis")
```

**Comment by ajays7671** [comment]
I uninstalled all courses and re-installed but, still not working
as

| Hi! Type swirl() when you are ready to begin.

> uninstall_all_courses()
All courses uninstalled successfully!
> install_from_swirl("Getting and Cleaning Data")
Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/Ajay/Documents/R/win-library/3.2/swirl/Courses/temp.zip' cannot be opened
>

**Comment by seankross** [comment]
@ajays7671 Are you running R/Rstudio as administrator?

**Comment by ajays7671** [comment]
Thanks @seankross , i used all **suggestions** given at different times by you and it worked me.Now, i am happily using swirl.Thanks.

**Comment by seankross** [comment]
@asweng, I'm closing this issue but if you need further assistance please let me know and I will reopen it.

**Comment by PM20160115** [comment]
I am getting the same error 
uninstall_all_courses()
All courses uninstalled successfully!
install_from_swirl("Getting and Cleaning Data")
Error in unzip(path, list = TRUE) : 
zip file 'C:/Users/<my name>/Documents/R/win-library/3.2/swirl/Courses/temp.zip' cannot be opened

@seankross what is the suggestion provided  to fix this issue ?
Appreciate the help
