### ISSUE TITLE
R Programming module 4 containing paste yields error when making "My name is"

### ISSUE THREAD

**Issue by dcowles** [swirldev/swirl_courses#207]
In module 4. Vectors:   I assume this behavior I encountered was because I used my first and last name separated by a space: 

| To add (or 'concatenate') your name to the end of my_char, use the c() function like this: c(my_char,
| "your_name_here"). Place your name in double quotes where I've put "your_name_here". Try it now, storing the
| result in a new variable called my_name.

> my_name<-c(my_char,"Doug Cowles")

| Keep up the great work!

  |=============================================================================                         |  76%

| Take a look at the contents of my_name.

warning messages from top-level task callback 'mini'
Warning message:
In stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE) :
  longer object length is not a multiple of shorter object length

I'm guessing that's because I had a space between my first and last name. 
Maybe something to fix or indicate only to use one string of letters?

**Comment by seankross** [comment]
This doesn't have to do with a space in your name, this is a known bug in
swirl and we're working on a solution.Were you able to finish this lesson?

**Comment by dcowles** [comment]
Yes I was.. thanks.

- D
