### ISSUE TITLE
Writing_swirl_Courses crashes my rsession

### ISSUE THREAD

**Issue by Kenkleinman** [swirldev/swirl_courses#215]
When trying to bring up the text file in my editor.

I'm using RStudio on a Windows 7 Pro machine (University owned).

**Comment by seankross** [comment]
Does it crash your session after trying to start the first lesson?

**Comment by Kenkleinman** [comment]
Now that I've started the lesson once and got to that point, yes, it crashes immediately upon starting the course.  I believe the problem is associate with not finding the file in the expected location-- there's an error message to that effect.  i can't cut and paste, because it's dead, but here's the gist:

Error: File swirl_temp/lesson.yaml does not exist
In addition: warning message:
In file.copy(...
  problem copying ...
      : No such file or directory

Then it hangs.

**Comment by seankross** [comment]
Could you take and send a screenshot?

**Comment by seankross** [comment]
Also I have to ask - are you interested in writing swirl courses? There are going to be significantly better instructions for writing swirl courses next week.

**Comment by Kenkleinman** [comment]
I'm happy to wait.  I was mostly procrastinating.  

![image](https://cloud.githubusercontent.com/assets/513714/10648734/39dceec4-780e-11e5-8863-f7e441e07d55.png)

(Not sure that screen capture & paste worked)

**Comment by seankross** [comment]
I see what's going on here and this course needs to be reworked as it is. I'll have something better for you next week.

**Comment by Kenkleinman** [comment]
Awesome!

_______________________________________________________
_______________________________________________________
Ken Kleinman, ScD
Associate Professor, Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

Lecturer, Department of Population Medicine
Harvard Medical School

My blog on SAS and R: http://sas-and-r.blogspot.com
My professional web home: http://www.kenkleinman.net/home/
My cites on Google Scholar: http://tinyurl.com/KenK-cites
__________________________________________________
** Electronic Mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues. **

**Comment by smuch** [comment]
I have the same problem and sense it has something to do with user rights (though I open RStudio with admin rights). Copying the files manually works and the files are opened automatically within the lessons.
Anyway, I'm also looking forward to the new instructions! :)

**Comment by seankross** [comment]
Hi @Kenkleinman and @smuch,

Authoring lessons should be done with [swirlify](https://github.com/swirldev/swirlify). I'm currently preparing swirlify to be released on CRAN, while working on the documentation at the same time. You can find the preliminary documentation [here](https://github.com/swirldev/swirlify/wiki).

**Comment by smuch** [comment]
Hi @seankross,
thanks for your the update regarding swirlify! I already use it but the documentation is definitely helpful! Thank you!

**Comment by seankross** [comment]
Hi @smuch,

The swirlify API is about to change significantly and the documentation is geared towards the new API. Our goal was for the new API to be easier to use!
