### ISSUE TITLE
Get multiple courses into a single zip file? 

### ISSUE THREAD

**Issue by HJ08003** [swirldev/swirl_courses#218]
Can I zip_course multiple courses into a single zip file? If so, how to do it?

We are make zip files so that people can get install_course_guthub to install multiple courses.

**Comment by seankross** [comment]
Currently there's no good way to package multiple courses together. I would suggest instructing your students to source a script like this:

```r
library(swirl)
course <- c("Course_1", "Course_2", "Course_3")

for(i in course){
  install_course_github("HJ08003", i)
}
```

This process will be much easier in the next version of swirl.

**Comment by HJ08003** [comment]
Hi Sean,

Thank you very much for the answer.

Is there a way students can install courses from a folder (i.e. similar to unzipped directory) from a Github repo?

This way, we can upload the whole directory which has several sub-directories (i.e. one per each course) to Github, without making zip files.

Thanks again.

 -Hubert

________________________________

**Comment by seankross** [comment]
That's a good idea! You can have students download the zip file of the Github repository, unzip the file, and then they can do something like:

```r
library(swirl)
setwd(file.path("~", "Downloads", "swirlcourses"))

for(i in dir()[file.info(dir())$isdir]){
  install_course_directory(i)
}
```

Let me know if you need any help setting your student up with this.

**Comment by HJ08003** [comment]
Hi Sean,

Right now, the Github is organized as the following
    https://github.com/kosukeimai/qss/tree/master/swirl

In install_course_github, the code looks for paste0("http://github.com/", github_username, "/", course_name,"/zipball/", branch), which will be "http://github.com/username/coursename/zipball/master"<http://github.com/user_name/course_name/zipball/master.>

Thus, we need put courses' zip files under the folders at Github, such as username/cours1/zipball/master/course1.zip, username/cours2/zipball/master/course2.zip, username/cours2/zipball/master/course2.zip, etc.

Then, install_course_github will work directly giving the input of github_username and course_name.

Please let me know if my understanding isn't correct.

Thanks,

-Hubert




________________________________

**Comment by seankross** [comment]
Hi Hubert,

So the idea of `install_course_github()` is that every course is in its own Github repository. I think your students should download the zip file from this url: http://github.com/kosukeimai/qss/zipball/master and then have you students execute the following code:

```r
library(swirl)

path <- file.choose()
dirpath <- dirname(unzip(path, exdir = dirname(path))[1])
for(i in list.files(file.path(dirpath, "swirl"), full.names = TRUE)){
  install_course_directory(i)
}
```

When they execute `path <- file.choose()` they will be prompted to select a file, and they should select the zip file they just downloaded. Let me know if that solution works for you.

**Comment by HJ08003** [comment]
Thank you very much.

-Hubert

**Comment by HJ08003** [comment]
Hi Sean,

We intended to merge all the lessons under a single course and call it QSS. Thus, we can still let people use install_course_github and not to deal with multiple courses.

As I am organizing the course/lesson files, I notice the following

- Class: meta
  Course: CAUSALITY
  Lesson: CAUSALITY1

Obviously, I will change the above to "Course: QSS" and keep the Lesson as it is right now. But how about the Class field? Is it just for information only or does it play some role in the organization of the course materials?

Thank you very much,

-Hubert

**Comment by seankross** [comment]
Hi Hubert,

The `Class` field pertains to the type of question in the lesson, so that swirl knows whether the question is asking for an R command, or it's a multiple choice question, etc. The `Class: meta` "question" within the lesson gives basic information about the lesson and isn't shown to the student while they're using swirl.

**Comment by HJ08003** [comment]
Hi Sean

We have a QSS.zip which works when I install the course using install_course_zip from zipball/master/QSS.zip in my local directory.

When I upload the zip file to a local server  http://pol-c07jw0gqf4mg.princeton.edu:8000/, install_course_url also worked well.

But when I upload the whole folder including zip file (zipball/master/QSS.zip) to my github QSS https://github.com/HJ08003/QSS , it shown up as
     https://github.com/HJ08003/QSS/blob/master/zipball/master/QSS.zip

I don’t know where the “blob" came from. But this url is quite different from "http://github.com/HJ08003/QSS/zipball/master” as the specified in the function


> install_course_github

function (github_username, course_name, branch = "master", multi = FALSE)

{

    zip_url <- paste0("http://github.com/", github_username,

        "/", course_name, "/zipball/", branch)

    install_course_url(zip_url, multi = multi)

}

<environment: namespace:swirl>

So, install_course_url and install_course_github both not working for me through github website as shown below.

Could you help us spot what went wrong? We really want to let people install the course from the single command install_course_github.

Thanks you very much,

-Hubert


>

> install_course_zip("/Users/hubertj/Desktop/NewProject/mytest/zipball/master/QSS.zip")

>

> uninstall_course("QSS")

Course uninstalled successfully!

>

>

> install_course_url("http://pol-c07jw0gqf4mg.princeton.edu:8000/QSS.zip")

  |======================================================================| 100%>

>

> uninstall_course("QSS")

Course uninstalled successfully!

>

> install_course_url("https://github.com/HJ08003/QSS/blob/master/zipball/master/QSS.zip")

Downloading: 7.7 kB     Error in unzip(path, list = TRUE) :

  zip file '/Users/hubertj/Library/R/3.1/library/swirl/Courses/temp.zip' cannot be opened

In addition: Warning message:

In unzip(path, exdir = get_swirl_option("courses_dir")) :

  error 1 in extracting from zip file

>

> uninstall_course("QSS")

Error in uninstall_course("QSS") : Course not found!

>

> install_course_github("HJ08003", "QSS")

  |======================================================================| 100%perl is deprecated. Please use regexp instead

>

> swirl()


| Welcome to swirl!


| Please sign in. If you've been here before, use the same name as you did

| then. If you are new, call yourself something unique.


What shall I call you?


| Please choose a course, or type 0 to exit swirl.


1: QSS

2: R Programming

3: swirl

4: Take me to the swirl course repository!


Selection: 1


| Please choose a lesson, or type 0 to return to course menu.


1: zipball


Selection: 1


Error in file(con, "r") : invalid 'description' argument


| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
Hi Hubert,

I just sent you a pull request that should make things work: https://github.com/HJ08003/QSS/pull/1
Also, should these lessons be completed in a particular order?

**Comment by HJ08003** [comment]
Sean,

Thank you very much. It works now. What did you do?

It will be great if the lessons are in a particular order, which is not in order at this moment.

-Hubert

**Comment by seankross** [comment]
Hi Hubert,

You have a QSS folder on your computer containing all of the lesson folders right? Just treat that as a Git repository and commit it to GitHub. No need to zip the folder or to share a zip file. Also I sent you a pull request which deletes some unnecessary files: https://github.com/HJ08003/QSS/pull/2

**Comment by HJ08003** [comment]
Hi Sean,

Thank you very much for your help.

Is there a way to order the lessons so that they are numbered correctly when people install the courses? Right now, the lessons are listed alphabetically, which is not ideal.

Thanks,

-Hubert

**Comment by seankross** [comment]
Hi Hubert,

So if you include a `MANIFEST` file in the course you can specify the order of the lessons. If you let me know what order you want the lessons to appear in I can send you a pull request with the appropriate `MANIFEST` file, and in the future if you want to add lessons you can edit the `MANIFEST` file.

**Comment by HJ08003** [comment]
Hi Sean,

Below is the order of the lessons. Thank you very much,

-Hubert

==========

INTRO1

INTRO2

CAUSALITY1

CAUSALITY2

MEASUREMENT1

MEASUREMENT2

PREDICTION1

PREDICTION2

PREDICTION3

DISCOVERY1

DISCOVERY2

DISCOVERY3

PROBABILITY1

PROBABILITY2

UNCERTAINTY1

UNCERTAINTY2

UNCERTAINTY3

**Comment by seankross** [comment]
I just sent the pull request: https://github.com/HJ08003/QSS/pull/3

**Comment by HJ08003** [comment]
Sean,

Thank you very much. It works out nicely.

-Hubert

**Comment by seankross** [comment]
No problem! I'm going to close this issue but feel free to continue writing messages here if you have more questions.
