### ISSUE TITLE
Answering NA to a question

### ISSUE THREAD

**Issue by HJ08003** [swirldev/swirl_courses#221]
We encountered a problem that entering NA will cause swirl to think it is the right answer. However, it is not always that way. Thus, could you look at the portion of the YAML we have? (Question 3 has the problem, but question 6 doesn't)

I tried changing "exact_question" to "cmd_question" for question 3, but it didn't help. 

Thank you very much.

-Hubert

=============================================
\- Class: meta
  Course: qss-swirl
  Lesson: PREDICTION1
  Author: EC and KI
  Type: Standard
  Organization: Princeton University
  Version: 2.2.21

\- Class: text
  Output: 'The following exercises are a companion to Chapter 4: Prediction.'
  
\# Question 1
\- Class: mult_question
  Output: 'True or False: Loops can simplify our programming code when we want to repeatedly execute code chunks over and over again.'
  AnswerChoices: '"True"; "False"'
  CorrectAnswer: 'True'
  AnswerTests: omnitest(correctVal='"True"')
  Hint: See 'Loop in R'

\# Question 2
\- Class: mult_question
  Output: 'To iterate means to _____.'
  AnswerChoices: 'perform repeatedly; perform once; skip over'
  CorrectAnswer: perform repeatedly
  AnswerTests: omnitest(correctVal='perform repeatedly')
  Hint: See 'Loop in R'

\# Question 3
\- Class: exact_question
  Output: 'Given that "n <- 10", how many times will the loop "for (i in 1:n)" iterate through?'
  CorrectAnswer: '10'
  AnswerTests: omnitest(correctVal='10')
  Hint: See 'Loop in R'

\# Question 4
\- Class: mult_question
  Output: 'In the conditional expression "if (Y) {expression1}", "expression1" will be executed if "Y" is _____.'
  AnswerChoices: 'True; False'
  CorrectAnswer: 'True'
  AnswerTests: omnitest(correctVal='True')
  Hint: See 'General Conditional Statements in R' 

\# Question 5
\- Class: mult_question
  Output: 'A conditional statement that is nested within a loop is executed _____ the loop.'
  AnswerChoices: 'inside; outside'
  CorrectAnswer: inside
  AnswerTests: omnitest(correctVal='inside')
  Hint: See 'General Conditional Statements in R' 

\#\# Programming Questions
\- Class: text
  Output: 'It is often useful to create an empty vector to store the computational output from a loop'

\# Question 6
\- Class: cmd_question
  Output: 'Create a vector called "output" that is filled with "NA"s and has the length "n". The object "n" has been included in this lesson.'
  CorrectAnswer: output <- rep(NA, n)
  AnswerTests: omnitest(correctExpr='output <- rep(NA,n)')
  Hint: See 'Loop in R'

**Comment by seankross** [comment]
This is strange. I'm investigating.

**Comment by seankross** [comment]
Hi Hubert,

I'm still trying to figure out if this is a bonafide bug, but in the mean time I sent you a pull request that should solve this issue: HJ08003/QSS#4

**Comment by HJ08003** [comment]
Hi Sean,

One of our preceptors came up with a solution like this by adding [CorrectAnswer: ‘0.25’]

# Question 9
- Class: exact_question
  Output: 'Now, I flip a coin of unknown bias 10 times. It comes up heads 8 times. What is the (non-negative) margin of error, calculated from a 95% confidence interval for the true probability the coin comes up heads (to the nearest 0.01)?'
  CorrectAnswer: '0.25'
  AnswerTests: omnitest(correctVal='0.25')
  Hint: See 7.1.3.

How do you think this solution? Is this equivalent to yours?

Thanks,

-Hubert

**Comment by seankross** [comment]
Both solutions are equivalent, but of course use whichever suits you best.
