### ISSUE TITLE
Change in 3Tidying data in Getting and Cleaning data

### ISSUE THREAD

**Issue by Marcelophant** [swirldev/swirl_courses#225]
I'd like to suggest a change the "fifth messy data scenario" in Lesson 3 of the Getting and Cleaning Data course. This change referes to Line 208 onwards of lesson.yaml
Instead of adding a column called "status" with the possible string values "passed" or "failed" there should be a column called "passed" with values TRUE or FALSE. As this is a variable that can only take two values, using a boolean helps avoid spelling mistakes and facilitates further evaluation.

**Comment by seankross** [comment]
In the context of the problem, I'm not sure that using boolean values make sense.
