### ISSUE TITLE
[URGENT] Students are unable to get credit for swirl in courses updated to "Coursera on-demand"

### ISSUE THREAD

**Issue by yli3** [swirldev/swirl_courses#228]
Hi,

I'm a current CTA in the rprog-035 course. A great many students have just started reporting they are unable to receive credit for work in swirl. I have tried, and also can't figure out a way. 

This appears to be completely broken, and the hard deadline for this is in about one day -- Sun 3 Jan 2016 4:30 PM PST.

swirl itself has a latest commit of Aug 19, 2015. This R course has a new commit from as of 2 days ago, and it's labeled "added Coursera on-demand".

There is new language in files corresponding to this (e.g: https://github.com/swirldev/swirl_courses/blob/2680dc3022c445f1e603c9c7405dc0b5017b2cde/R_Programming/lapply_and_sapply/customTests.R) that are inconsistent with current instructions. We're all mystified as to what "assignment token" means; we are no longer asked for either the Course-ID or the submission password. Further, blank entries as well as gibberish entries are accepted as correct.

If this is an update for swirl to the new Coursera platform, it was done prematurely -- the last round of the classes on the old platform have not ended yet, and there are many confused students who are attempting and unable to complete swirl credit in rprog-035. 

This appears to be the only swirl course affected. [Edit: actually, it looks like a few more are affected as well.]

If that's indeed the issue, please roll it back until after the hard deadline of Sun 3 Jan 2016 4:30 PM PST has passed! Thank you!

**Comment by seankross** [comment]
Sorry for the confusion. This should be fixed now.

**Comment by yli3** [comment]
Hey sean, that's outstanding -- thank you for the prompt response, and happy new year!

**Comment by yli3** [comment]
I don't know if you have any control over this, by the way, but perhaps email instructions to uninstall and reinstall swirl courses if affected (i.e, encountering a request for "assignment tokens") pushed through Coursera would be helpful. I've put up instructions on the fora, but not everyone reads that. 

Thanks again!

**Comment by mvpboston** [comment]
Hi Sean,

I just completed my assignment on Coursera for basic building blocks for R however I am unable to get the credit for it even though I entered my email id and token. Can you please help?

| Would you like to receive credit for completing this course on
| Coursera.org?
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

Thanks,
Manisha

**Comment by seankross** [comment]
Hi Manisha,

You may need to use another internet connection in order to submit the assignment. Sorry for the inconvenience.

**Comment by mvpboston** [comment]
Oh ok I understand it could be due to the fact that I'm using my work laptop so there maybe a firewalls issue. 
So I will have to figure out how to reconnect back to my working session and get the credits if I use a personal laptop. 
Thanks Sean! Appreciate your quick response.

**Comment by OlgaCh** [comment]
Hi @seankross 
what's the workaround if I can't switch to another internet connection?
I'm using home server to work on swirl assignments but can't get credit for any of them because of timeout error.
Thanks!

**Comment by seankross** [comment]
Hi @OlgaCh,

I'm working on a workaround today and the rest of this week! I hope to be able to close many of these issues soon.

Sean

**Comment by geetapuri** [comment]
Hi, 
I was working on 3 swirl assignments when my internet connection was not working.  I thought I would submit the tokens later.  Is there no way of getting credit for past swirl lessons?

Thanks,
Geeta

**Comment by seankross** [comment]
Hi @geetapuri,

If you resume the lessons you should be able to submit for credit again.

Sean

**Comment by geetapuri** [comment]
Hi Sean,

Thanks for your reply.  When I enter the lesson again, it just asks me to redo the whole thing from start!

Is submitting the token(for the swirl lessons in Week 3) necessary for passing the 4th Module - Exploratory Analysis? 

Thanks,
Geeta

**Comment by seankross** [comment]
So to be clear, when you start swirl does it ask if you want to resume a
lesson?

Sean

**Comment by geetapuri** [comment]
No, it just starts the lesson from the beginning - 0%

**Comment by shancoder97** [comment]
sir i am not able to install swirl i tried alot and also test you solution on my laptop
when i put install.package("swirl")
it shows me this

Installing package into ‘/home/shantanu/R/x86_64-pc-linux-gnu-library/3.2’ (as ‘lib’ is unspecified) --2017-09-13 19:54:04--  https://cran.cnr.berkeley.edu/src/contrib/swirl_2.4.3.tar.gz Resolving cran.cnr.berkeley.edu (cran.cnr.berkeley.edu)... 169.229.19.202, 2607:f140:0:11::c Connecting to cran.cnr.berkeley.edu (cran.cnr.berkeley.edu)\|169.229.19.202\|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 108666 (106K) [application/x-gzip] Saving to: ‘/tmp/RtmpReMHsa/downloaded_packages/swirl_2.4.3.tar.gz’       0K .......... .......... .......... .......... .......... 47% 71.9K 1s     50K .......... .......... .......... .......... .......... 94%  291K 0s    100K ......                                                100% 65.6M=0.9s  2017-09-13 19:54:08 (122 KB/s) - ‘/tmp/RtmpReMHsa/downloaded_packages/swirl_2.4.3.tar.gz’ saved [108666/108666]  * installing *source* package ‘swirl’ ... ** package ‘swirl’ successfully unpacked and MD5 sums checked ** R ** inst ** preparing package for lazy loading Warning: S3 methods ‘as.data.frame.testthat_results’, ‘as.expectation.default’, ‘as.expectation.error’, ‘as.expectation.expectation’, ‘as.expectation.logical’, ‘as.expectation.skip’, ‘as.expectation.warning’, ‘compare.POSIXt’, ‘compare.character’, ‘compare.default’, ‘compare.numeric’, ‘format.expectation’, ‘format.expectation_error’, ‘format.expectation_success’, ‘format.mismatch_character’, ‘format.mismatch_numeric’, ‘print.comparison’, ���print.expectation’, ‘print.mismatch_character’, ‘print.mismatch_numeric’, ‘print.testthat_results’ were declared in NAMESPACE but not found
 Error in library.dynam(lib, package, package.lib) :    shared object ‘testthat.so’ not found
 ERROR: lazy loading failed for package ‘swirl’ * removing ‘/home/shantanu/R/x86_64-pc-linux-gnu-library/3.2/swirl’ 
Warning in install.packages :   installation of package ‘swirl’ had non-zero exit status  The downloaded source packages are in 	‘/tmp/RtmpReMHsa/downloaded_packages’

**Comment by shiwani-w** [comment]
Hey, 
I am unable to get the credit for swirl exercise
Every time I try, it says the following thing-
#Grade submission failed.
#Press ESC if you want to exit this lesson and you
#want to try to submit your grade at a later time.

# Nice try, but that's not exactly what I was hoping for. Try again.

Please suggest some way to solve this problem, the deadline is  11th march for the submission

**Comment by duxingmoyu** [comment]
> Hey,
> I am unable to get the credit for swirl exercise
> Every time I try, it says the following thing-
> #Grade submission failed.
> #Press ESC if you want to exit this lesson and you
> #want to try to submit your grade at a later time.
> 
> # Nice try, but that's not exactly what I was hoping for. Try again.
> Please suggest some way to solve this problem, the deadline is 11th march for the submission

Maby you should uninstall the swirl package and install it again. Sometime high version of R may cause kinds of questions，you should use lower version such as 3.2.0 .
