### ISSUE TITLE
Message "perl is deprecated. Please use regexp instead"

### ISSUE THREAD

**Issue by HJ08003** [swirldev/swirl_courses#232]
Hello,

When we install a course from Github by install_course_github, we see a warning message.

> install_course_github("kosukeimai", "qss-swirl")
perl is deprecated. Please use regexp instead

install_course_github calls install_course_url, which is the source of this message. 

It is not causing any problems, but it would be nice not to have it. Any suggestions

Thanks,

-HJ

**Comment by seankross** [comment]
Hi HJ,

This is going to be fixed in the new version of swirl which will be released later this month. This warning has no affect on swirl's behavior.

Sean

**Comment by HJ08003** [comment]
Thank you very much,

-Hubert
