### ISSUE TITLE
Cannot install "plotrix" package for Central Tendency lesson in Data Analysis cours

### ISSUE THREAD

**Issue by AChapsK** [swirldev/swirl_courses#236]
I'm trying to take the "Central Tendency" lesson in Data Analysis, and cannot install the "plotrix" package when prompted in the lesson. When swirl tries to install it, I get the following:
_____________________________________________________________________
 Attemping to load lesson dependencies...

| This lesson requires the ‘plotrix’ package. Would you like me to install it
| for you now?

1: Yes
2: No

Selection: 1

| Trying to install package ‘plotrix’ now...
--- Please select a CRAN mirror for use in this session ---
Warning: unable to access index for repository http://cran.mirrorcatalogs.com/bin/windows/contrib/3.1

| Could not install package ‘plotrix’!

  |                                                                            
  |                                                                      |   0%Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1
In addition: Warning message:
package ‘plotrix’ is not available (as a binary package for R version 3.1.3) 

| Leaving swirl now. Type swirl() to resume.
_______________________________________________________________

I tried also tried install.packages("plotrix") and got the following:
________________________________________________________________

> install.packages("plotrix")
Installing package into ‘C:/Users/aknight/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://cran.mirrorcatalogs.com/bin/windows/contrib/3.1
Warning message:
package ‘plotrix’ is not available (as a binary package for R version 3.1.3) 
_______________________________________________________________________

Help! Thanks!

**Comment by seankross** [comment]
My best advice is to upgrade the latest version of R. Are you able to do that?

**Comment by AChapsK** [comment]
No - I don't have administrative control over the computer I'm using, so I can't install or upgrade programs.Thanks for the suggestion. Any other ideas?

**Comment by seankross** [comment]
You could try installing an old version of plotrix, though I don't know which version would be old enough.

- Here is the list of binaries for old versions of plotrix: https://cran.r-project.org/src/contrib/Archive/plotrix/
- Here are instructions for installing: http://stackoverflow.com/questions/1474081/how-do-i-install-an-r-package-from-source

**Comment by AChapsK** [comment]
Success! Thanks!

**Comment by seankross** [comment]
No problem! Let me know if you have any other issues.
