### ISSUE TITLE
Error while trying to install a course

### ISSUE THREAD

**Issue by JuanCastellanosM** [swirldev/swirl_courses#245]
Hi

I've been trying to install some courses but i keep receiving an error message:

> library(swirl)
> install_from_swirl("R Programming")
Error en unzip(path, exdir = file.path(path.package("swirl"), "Courses"),  : 
  argumento 'files' inválido

The same error shows up when i try to install it from the zip file. I tried in R and Rstudio and the result is the same. I even uninstalled swirl and installed it again but it did not work.

I would appreciate your help :'(

**Comment by seankross** [comment]
Are you using a computer from work or school?

**Comment by JuanCastellanosM** [comment]
No, i am using my own pc

**Comment by ajays7671** [comment]
facing same problem, platform-windows 8, 32 bit .Both ways of installing courses are not working.

**Comment by s0023655** [comment]
I'm facing similar problems; various error messages; most common is "Error: could not find function "install_from_swirl""
Platform Windows 7 Enterprise; 64bit

**Comment by seankross** [comment]
@s0023655 Are you sure you're entering `library(swirl)` before `install_from_swirl()`?

**Comment by seankross** [comment]
@JuanCastellanosM What do you get as the result of the following?:

```r
library(swirl)
file.exists(file.path(path.package("swirl"), "Courses"))
```

**Comment by JuanCastellanosM** [comment]
@seankross I get a message that says "TRUE"

**Comment by seankross** [comment]
@JuanCastellanosM try following my instructions in swirldev/swirl#387

**Comment by JuanCastellanosM** [comment]
Hi @seankross .
I tried your instructions and this is what i got:

> library(swirl)
> install_course_zip(file.choose(), multi = TRUE, which_course = "R Programming")
Error en install_course_zip(file.choose(), multi = TRUE, which_course = "R Programming") : 
  el argumento(s) no fue utilizado(s) (which_course = "R Programming")

If I use the same command without the option which_course I'm able to choose the zip file, but then i get another error

> install_course_zip(file.choose(), multi = TRUE)
Error en unzip(path, exdir = file.path(path.package("swirl"), "Courses"),  : 
  argumento 'files' inválido

Then, if I do not use the option multi=TRUE I get this

> install_course_zip(file.choose())
Course installed successfully!

But then i try opening the Getting and Cleaning Data course and I get another error

> swirl()

| Welcome to swirl! Please sign in. If you've been here before, use the same name as you did
| then. If you are new, call yourself something unique.

What shall I call you? Juan

| Would you like to continue with one of these lessons?

1: Data Analysis Central Tendency
2: Mathematical Biostatistics Boot Camp One Sample t-test
3: Open Intro Overview of Statistics
4: No. Let me start something new.

Selección: 4

| Please choose a course, or type 0 to exit swirl. We recommend Intro to R, which is the only
| course we are actively developing.

1: Data Analysis
2: Intro to R
3: Mathematical Biostatistics Boot Camp
4: Open Intro
5: swirl courses-master
6: swirldev-swirl courses-e44d379
7: Test Lessons

Selección: 5

| Please choose a lesson, or type 0 to return to course menu.

 1: Data Analysis                          2: ErrFind                             
 3: Exploratory Data Analysis              4: Getting and Cleaning Data           
 5: LICENSE                                6: Mathematical Biostatistics Boot Camp
 7: Open Intro                             8: R Programming                       
 9: R Programming Alt                     10: README.md                           
11: Regression Models                     12: Statistical Inference               
13: Writing swirl Courses                 

Selección: 4
Error en parse_content.default(dataName, e) : Incorrect content class!

| Leaving swirl now. Type swirl() to resume.

PD: Sorry that some of the outcomes are in spanish but i do not know how to change it.

**Comment by seankross** [comment]
What do you get as the result of `packageVersion("swirl")` ?

**Comment by rajamaniv** [comment]
It's 2.2.21

**Comment by JuanCastellanosM** [comment]
@seankross I get 2.1.1

**Comment by seankross** [comment]
@JuanCastellanosM you should upgrade your version of swirl: `install.packages("swirl")`.

**Comment by JuanCastellanosM** [comment]
@seankross I tried the command and it installed version 2.1.1 again, so i tried installing it with the following commands i found

> install.packages("devtools")
> library(devtools)
> install_github("swirldev/swirl")
> library(swirl)
> swirl()

and it said that i needed to get the latest R version. I thought i had the latest version since i re-installed it recently but i don't know what went wrong. So, problem solved when i updated R. 

Thanks for your help!

**Comment by seankross** [comment]
Hi @JuanCastellanosM, I can't guarantee that the version of swirl you've installed is stable, though you're welcome to use it. If you want to use the latest stable version of swirl you can install it using devtools:

```r
library(devtools)
install_github("swirldev/swirl", ref = "2.2.21")
```
