### ISSUE TITLE
Issue in Exploratory Data Analysis: Working with Colors

### ISSUE THREAD

**Issue by stats2016** [swirldev/swirl_courses#248]
Hi,
I am trying to do this lesson, and it keeps getting stuck at the "Create the function p3 now by calling colorRampPalette with the colors blue and green (remember to concatenate them into a single argument) and setting the alpha argument to .5."

I am entering the right command (I double-checked w/ what it said you should enter) and I keep getting this message:
Error in colorRamp(colors, ...) : unused argument (alpha = 0.5)

If I try to do skip() it just keeps exiting swirl. Even if I try to say skip() before entering any answer, it gives the same error message - so there is no way to complete the lesson.

**Comment by stats2016** [comment]
I have tried restarting R and re-doing the lesson. Nothing seems to be working.

**Comment by seankross** [comment]
Hi @stats2016,

What do you get as a result of `sessionInfo()`?

**Comment by stats2016** [comment]
Full message below:

> sessionInfo()
R version 3.0.3 (2014-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RColorBrewer_1.1-2 jpeg_0.1-8         swirl_2.2.21      

loaded via a namespace (and not attached):
[1] bitops_1.0-6   digest_0.6.8   httr_0.6.1     RCurl_1.95-4.5 stringr_0.6.2  testthat_0.8.1 tools_3.0.3    yaml_2.1.13   

| That's not exactly what I'm looking for. Try again. Or, type info() for more options.

| Type p3 <- colorRampPalette(c("blue","green"),alpha=.5) at the command prompt.

**Comment by stats2016** [comment]
I copy/pasted the last line in the command line and I got the same error message:

> p3 <- colorRampPalette(c("blue","green"),alpha=.5)
Error in colorRamp(colors, ...) : unused argument (alpha = 0.5)

**Comment by seankross** [comment]
@stats2016 Try installing the latest version of R and let me know if that helps.

**Comment by stats2016** [comment]
No - it still doesn't work, even though I'm now running version 3.0.3.

**Comment by seankross** [comment]
Can you install R 3.2.3, which is the latest version?

**Comment by stats2016** [comment]
Ok, that worked, thank you!
