### ISSUE TITLE
Incomplete last Row in R_Programming/Simulation/lesson.yaml

### ISSUE THREAD

**Issue by JimKnopf2034** [swirldev/swirl_courses#250]
It's just a warning but it's a bit confusing

The German warning:

`Warnmeldung vom toplevel task callback 'mini'
Warnmeldung:
In readLines(input) :
  unvollständige letzte Zeile in '<path>/swirl/Courses/R_Programming/Simulation/lesson.yaml' gefunden`

The Warning occures in the first cmd_question

**Comment by seankross** [comment]
How recently did you download this course? I believe I just fixed this issue.

**Comment by JimKnopf2034** [comment]
Hmm, ok, right my version is one day older than the latest, probably you fixed it already.
