### ISSUE TITLE
Error when sending request to receive credit for completing this course on Coursera.org

### ISSUE THREAD

**Issue by Pshubhranshu** [swirldev/swirl_courses#251]
Getting Timeout Error when sending request to receive credit for completing this course on Coursera.org

| Would you like to receive credit for completing this course on Coursera.org?

1: Yes
2: No

Selection: 1
What is your email address? abc@gmail.com
What is your assignment token? ...........
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

**Comment by seankross** [comment]
Hi @Pshubhranshu,

Right now we're working on enabling manual submission for completion of swirl lessons, but we don't have a solution at this time. Consult [this](https://github.com/swirldev/swirl/wiki/Coursera-FAQ) document to make sure you're not making any errors when you submit.

**Comment by Pshubhranshu** [comment]
Thanks for your valuable reply.
I already checked the document you shared and as per that at the time of submission, I mentioned the Token and Email as per Coursera. Tried this several times but it didn't work. So posted this query.

As per your reply, I will wait for your next reply with the steps for manual submission( once you have the solution).

But anyway, thanks a lot to Swril for the content of the study materials. Whether I get any official credit or not but from learning point of view it's really helps a lot.

**Comment by seankross** [comment]
Good to hear, if you have any other issues please let me know. This is an issue I'm actively working on so I'm going to close this issue.

**Comment by KariL89** [comment]
I'm having the same issue, is there any way I can submit the assignments?

**Comment by mtwestra** [comment]
I had the same issue, and it is annoying that swirl forces me to redo the whole module if I want a second chance. It should at least catch the error and offer to retry. 

Nevertheless, my compliments for a wonderful learning experience!

**Comment by Pavanyv22** [comment]
I'm having the same issue, is there any way I can submit the assignments?

**Comment by seankross** [comment]
Hi @Pavanyv22,

Can you try submitting using a different internet connection?

**Comment by Pavanyv22** [comment]
I tried from home internet connection, its works fine.  Believe this is getting blocked while doing it thru office internet connection. Thanks for your reply

**Comment by parabilal** [comment]
I am having the same issue in submitting the swirl assignment. Error in curl::curl_fetch_memory(url, handle = handle) :
Timeout was reached
Could u please help in resolving the issue.

**Comment by seankross** [comment]
@parabilal Have you tried using a different internet connection?

**Comment by parabilal** [comment]
@seankross , I tried but failed again, same error same issue.

**Comment by parabilal** [comment]
@seankross , Is there any manual procedure for submission of assignment?

**Comment by seankross** [comment]
@parabilal unfortunately there is no option for manual submission since these swirl assignments are only bonuses.

**Comment by dfleroux** [comment]
Getting Timeout Error when sending request to receive credit for completing this course on Coursera.org

| Would you like to receive credit for completing this course on Coursera.org?

1: Yes
 2: No

Selection: 1
 What is your email address? abc@gmail.com
 What is your assignment token? ...........
 Error in curl::curl_fetch_memory(url, handle = handle) :
 Timeout was reached

**Comment by seankross** [comment]
@dfleroux can you trying using a different internet connection?

**Comment by dfleroux** [comment]
Thank you for the reply.
I can try for a home computer. Are you concern about firewall issues from the Co. server or the like?
I will let you know.
Denis

**Comment by saulh-beltran** [comment]
Me acabo de enfrentar a este problema, la solución fue utilizar una conexión diferente (en mi caso vía celular), de manera tal que no hubo ninguno filtro de seguridad que me bloqueara el envío. 
Con lo anterior pude enviar mis ejercicios.

**Comment by seankross** [comment]
Google Translate translation of @saulh-beltran comment:

I just faced this problem, the solution was to use a different connection (in my case via cell), so that there was no security filter to block my sending.
With the above I was able to send my exercises.
