### ISSUE TITLE
install_from_swirl("Getting and Cleaning Data")  - error

### ISSUE THREAD

**Issue by PM20160115** [swirldev/swirl_courses#260]
I was trying install the Getting and Cleaning Data and getting following  error.  One thread I saw a suggestion to Uninstall_all_ courses  , I tried still I get the same error. Any help is appreciated 

MY steps : 
uninstall_all_courses()
All courses uninstalled successfully!
install_from_swirl("Getting and Cleaning Data")
Error in unzip(path, list = TRUE) : 
zip file 'C:/Users//Documents/R/win-library/3.2/swirl/Courses/temp.zip' cannot be opened

**Comment by seankross** [comment]
Are you using your own computer or a computer for work or school?

**Comment by PM20160115** [comment]
Computer from work

**Comment by seankross** [comment]
Try the following:

```r
install.packages("devtools")
library(devtools)
install_github("swirldev/swirl", ref = "dev")
library(swirl)
path <- file.path("~", "swirl", "Courses")
dir.create(path, recursive = TRUE)
swirl_options(swirl_courses_dir = path)
install_from_swirl("Getting and Cleaning Data")
swirl()
```

Let me know if that works.

**Comment by PM20160115** [comment]
Thanks for your response . When I executed the following command 
"install_github("swirldev/swirl", ref = "dev")"
Throws following error:

Downloading GitHub repo swirldev/swirl@dev
from URL https://api.github.com/repos/swirldev/swirl/zipball/dev
Installing swirl
Installing 3 packages: curl, openssl, RCurl
package ‘curl’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘curl’
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘RCurl’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘RCurl’
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/palanism/AppData/Local/Temp/RtmpwtQ2sz/devtools4a6854f24e76/swirldev-swirl-732786a"  \
  --library="C:/Program Files/R/R-3.2.3/library" --install-tests 

ERROR: dependency 'RCurl' is not available for package 'swirl'
* removing 'C:/Program Files/R/R-3.2.3/library/swirl'

**Comment by seankross** [comment]
Yikes, what happens if you try `install.packages("RCurl")`?

**Comment by PM20160115** [comment]
yes

**Comment by seankross** [comment]
So could you get RCurl installed?

**Comment by PM20160115** [comment]
I manually tried install.packages("RCurl")  
Looks like installed without an issue 

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.2/RCurl_1.95-4.8.zip'
Content type 'application/zip' length 2861404 bytes (2.7 MB)
downloaded 2.7 MB

package ‘RCurl’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘RCurl’

The downloaded binary packages are in
        C:\Users\palanism\AppData\Local\Temp\RtmpK4TFPf\downloaded_packages

Then I tried (it was working before)

install_from_swirl("R Programming") got the following error
Error in loadNamespace(name) : there is no package called ‘curl’

**Comment by seankross** [comment]
Try the following:

```r
path <- file.path("~", "swirl", "Courses")
dir.create(path, recursive = TRUE)
install.packages("RCurl", lib = file.path("~", "swirl"))

install_github("swirldev/swirl", ref = "dev")
library(swirl)
swirl_options(swirl_courses_dir = path)
install_from_swirl("Getting and Cleaning Data")
swirl()
```

**Comment by PM20160115** [comment]
I did  install.packages("curl")
then I did install_from_swirl("R Programming") went through fine
now I tried 
install_from_swirl("Getting and Cleaning Data") and successfully installed.

I didn't do following steps because I was getting error when I execute install_github("swirldev/swirl", ref = "dev")"


library(swirl)
path <- file.path("~", "swirl", "Courses")
dir.create(path, recursive = TRUE)
swirl_options(swirl_courses_dir = path)
install_from_swirl("Getting and Cleaning Data")
swirl()
 
One thing I did is close my R window and restarted it
Some how it is working

**Comment by PM20160115** [comment]
Any thoughts?

**Comment by seankross** [comment]
Hey if everything is working then it's working!

**Comment by PM20160115** [comment]
I know , thanks , If you can come up with some rational pl. let me know. Right now for me it is working but the question nagging is "how " and "why"

No worries Thanks for your support

**Comment by seankross** [comment]
I'm 99% sure it has to do with permissions on that computer, and there's no way for me how your employer has set up permissions. Your IT department will have better answers than I would.

**Comment by ChaiBapchya** [comment]
Unable to resolve issue
Despite restarting RStudio


```
library(swirl)

| Hi! I see that you have some variables saved in your workspace. To keep things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.

> path <- file.path("~", "swirl", "Courses")
> dir.create(path, recursive = TRUE)
Warning message:
In dir.create(path, recursive = TRUE) :
  '/root/swirl/Courses' already exists
> swirl_options(swirl_courses_dir = path)
> install_from_swirl("Getting and Cleaning Data")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
> swirl()

| Welcome to swirl! Please sign in. If you've been here before, use the same name as you did then. If you are new, call yourself something unique.

```

**Comment by seankross** [comment]
See swirldev/swirl#511
