### ISSUE TITLE
"Grouping and Chaining with dplyr"   Error in editor(file = file, title = title) : argument "name" is missing, with no default

### ISSUE THREAD

**Issue by rhkjr** [swirldev/swirl_courses#265]
I'm loving swirl.

But I've hit a problem in the "Grouping and Chaining with dplyr" lesson

I've exited/restarted Rstudio and rerun the lesson 3 times, same error reproduced each time.

Any idea for a solution or workaround?

Thanks,

Bob

*******

(pasted from swirl)

  |===========================================                                                                                                           |  29%

| Let's take it a step further. I just opened an R script for you that contains a partially constructed call to summarize(). Follow the instructions in the
| script comments.
| 
| When you are ready to move on, save the script and type submit(), or type reset() to reset the script to its original state.

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.

**Comment by adrianhuna** [comment]
Try this: https://github.com/swirldev/swirl/issues/434#issuecomment-201907367

**Comment by rhkjr** [comment]
Still not working.  Going to try removing and reloading swirl and lessons.

**Comment by rhkjr** [comment]
So removing/reinstalling did not fix the problem.

Using options(editor = "internal") did move the R code to a separate window, but it would not run with submit().  I copied and pasted the code to the console and it ran fine.

Another symptom: even after removing/reloading swirl and the lesson, when the R code sample pops up, it is already completed - so it's saving my previous attempt somewhere.  

I've been using swirl for a few weeks without incident and have completed this lesson before.

How do I completely remove swirl and it's footprints?  Last try I used:

uninstall_course("Grouping and Chaining with dplyr")  # for each course I had
detach("package:swirl",unload=T)
remove.packages("swirl")

**Comment by rhkjr** [comment]
Adrian, I appreciate your suggestion above, but that didn't work for my situation.

Other students in my coursera course are reporting the same issue on the coursera forums.  
The recommended solution there is to complete the swirl lessons "old school" in the R console and avoid loading swirl in RStudio.  I was able to complete the lesson this way.

As in stated in my previous post, I think this has something to do with the fact that this lesson was posted twice in the course requirements, optional for the first go round and mandatory for the second pass.  It runs smoothly on the first pass and bombs on the second pass.

Thanks,

Bob

**Comment by seankross** [comment]
> As in stated in my previous post, I think this has something to do with the fact that this lesson was posted twice in the course requirements, optional for the first go round and mandatory for the second pass. It runs smoothly on the first pass and bombs on the second pass.

Can you send a screenshot of what you're talking about here?

**Comment by MBJR1986** [comment]
I am having the exact same issue. Screenshot  attached... @seankross 

<img width="949" alt="capture" src="https://cloud.githubusercontent.com/assets/16244246/14462074/fd189b86-008a-11e6-9eee-0897f6ef8952.PNG">

**Comment by MBJR1986** [comment]
Issue resolved with adrian's previous thread.

**Comment by myemanresu** [comment]
I meet exacatly the same problem when running rstudio in win10 , and when I change Rstudio to R, everything go smoothly.
And perhaps this is not the first bug I found for Rstudio for Windows.

**Comment by seankross** [comment]
@myemanresu see https://github.com/swirldev/swirl/issues/434#issuecomment-201907367
