### ISSUE TITLE
"Error in Editor" Functions Lesson. Please help.

### ISSUE THREAD

**Issue by chrisalrutz** [swirldev/swirl_courses#266]
Hello,
Loving the swirl lessons so far but I seem to have an issue with the "Functions" lesson in "R Programming.
Once I get to this part of the lesson I receive the error message below:
**

> Functions usually take arguments which are variables that the function operates
> | on. For example, the mean() function takes a vector as an argument, like in the
> | case of mean(c(2,6,8)). The mean() function then adds up all of the numbers in the
> | vector and divides that sum by the length of the vector.
> 
> ...
> 
>   |=========                                                                  |  12%
> 
> | In the following question you will be asked to modify a script that will appear as
> | soon as you move on from this question. When you have finished modifying the
> | script, save your changes to the script and type submit() and the script will be
> | evaluated. There will be some comments in the script that opens up, so be sure to
> | read them!
> 
> ...
> 
>   |===========                                                                |  14%
> 
> | The last R expression to be evaluated in a function will become the return value
> | of that function. We want this function to take one argument, x, and return x
> | without modifying it. Delete the pound sign so that x is returned without any
> | modification. Make sure to save your script before you type submit().
> 
> Error in editor(file = file, title = title) : 
>   argument "name" is missing, with no default
> 
> | Leaving swirl now. Type swirl() to resume."
> 

**

I have tried shutting down RStudio and reinstalling the swirl package, I'm obviously pretty new to this so I don't know what else to try.

**Comment by seankross** [comment]
See #434

**Comment by shivdeepnv** [comment]
seankross has given the link to the article.

Try this - "Before you start swirl in RStudio, try entering options(editor = "internal"). Please let me know if that improves your situation."
