### ISSUE TITLE
Control Flow lesson in R Programming

### ISSUE THREAD

**Issue by im2fast4u** [swirldev/swirl_courses#284]
Hello,
Towards the end of lesson-8 (Logic) in R Programming course, it says this:

> That's all for this introduction to logic in R. If you really want to see what you can do with logic, check out the control flow lesson!

But I do not see a 'control flow' lesson in R Programming. Am I missing something or is it under a different name?

Thank you

**Comment by seankross** [comment]
It's not under a different name, it's still in development.

**Comment by im2fast4u** [comment]
Thank you Sean!
