### ISSUE TITLE
Exploratory Statistics: Lesson 2, Devoir: swirl Lesson 5: Base Plotting System

### ISSUE THREAD

**Issue by tbarnier** [swirldev/swirl_courses#288]
Hi,

I noticed a small problem in the swirl exercice:

The command 'data(mpg)' is not working by default,

as mpg is a dataset of the 'ggplot2' package

if you first go with the 'library(ggplot2) command, it works like a charm!

here is the log:
  |=============                                                                                  |  14%

| Now we'll go through some quick examples of basic plotting before we delve into gory details. We'll
| use the dataset airquality (part of the library datasets) which we've loaded for you. This shows ozone
| and other air measurements for New York City for 5 months in 1973.

...

  |==============                                                                                 |  15%

| Use the R command head with airquality as an argument to see what the data looks like.

messages d'avertissement du rappel (callback) de la tâche de niveau le plus haut 'mini'
Warning message:
In data(mpg) : data set ‘mpg’ not found

My 2 cents

Thierry Barnier

**Comment by seankross** [comment]
Hi @tbarnier,

This is a known issue that I'm working on, so I'm going to close this issue. Thanks for reporting this though.
