### ISSUE TITLE
expressions with parenthesis not accepted

### ISSUE THREAD

**Issue by beyond2013** [swirldev/swirl_courses#292]
In the Variance lesson of the Statistical Inference. Expression `ex2_fair - (3.5 ^ 2)` is the same as `ex2_fair - 3.5 ^ 2 `, but typing the expression with parenthesis results in **That's not the answer i was looking for...** Allowance for both expression would be nice.

**Comment by seankross** [comment]
Hi @beyond2013,

If you think something is wrong with how the answer to this question is tested, please send us a pull request that corrects the answer test.
