### ISSUE TITLE
Having trouble running the "Manipulating Data with dplyr" for "Getting and Cleaning Data"

### ISSUE THREAD

**Issue by DieselAnalytics** [swirldev/swirl_courses#295]
I installed the "Manipulating Data with dplyr" swirl course and I try to run it using the following commands:

`> library(swirl)
> swirl()`

I get the following responses from swirl as expected: 

| Welcome to swirl!

| Please sign in. If you've been here before, use the same name as you did then. If you are new, call yourself something unique.

What shall I call you? Tank

| Please choose a course, or type 0 to exit swirl.

1: Manipulating Data with dplyr
2: Take me to the swirl course repository!

When I choose option 1 I get the following response from swirl:

Selection: 1

| Please choose a lesson, or type 0 to return to course menu.

1: 2014-07-08.csv
2: customTests.R
3: dependson.txt
4: initLesson.R
5: lesson.yaml
6: outline.R

Selection:

Neither one of those selections get me to the course. What am I doing wrong? Is this a known issue? 
Any help will be appreciated. 

Regards,

Ryan

**Comment by seankross** [comment]
Try:

```r
library(swirl)
uninstall_all_courses()
install_course("Getting and Cleaning Data")
swirl()
```

**Comment by DieselAnalytics** [comment]
Thanks seankross!

**Comment by akhil9tiet** [comment]
https://github.com/swirldev/swirl_courses/blob/master/Getting_and_Cleaning_Data/Tidying_Data_with_tidyr/scripts/script4-correct.R

the code is not working for me...can you please help?

**Comment by seankross** [comment]
@akhil9tiet What happens if you restart swirl?

**Comment by akhil9tiet** [comment]
@seankross : It worked somehow. It has been a few days since I completed it. Sorry for the late reply. 
I am not very sure but I think, your progress is not hampered if you restart swirl. It will start from where you left off.

**Comment by hardikbatra17** [comment]
I tried to run the "Manipulating data with dplyr" course and the following happened-

swirl()
| Welcome to swirl! Please sign in. If you've been here before, use the same name
| as you did then. If you are new, call yourself something unique.
What shall I call you? Hardik

| Please choose a course, or type 0 to exit swirl.
1: Getting and Cleaning Data
2: R Programming
3: Take me to the swirl course repository!

Selection: 1

| Please choose a lesson, or type 0 to return to course menu.
1: Manipulating Data with dplyr
2: Grouping and Chaining with dplyr
3: Tidying Data with tidyr
4: Dates and Times with lubridate

Selection: 1

| Attempting to load lesson dependencies...

| This lesson requires the ‘dplyr’ package. Would you like me to install it for you
| now?
1: Yes
2: No

Selection: 1

| Trying to install package ‘dplyr’ now...
package ‘dplyr’ successfully unpacked and MD5 sums checked

| Could not install package ‘dplyr’!
  |                                                                          |   0%Error in seq.default(0, 1, length.out = nrow(e$les)) : 
  argument 'length.out' must be of length 1

| Leaving swirl now. Type swirl() to resume.

Although I have the dplyr package installed already but in any case "**| Leaving swirl now. Type swirl() to resume.**", this is what I get. How am I supposed to complete this course? Any help will be appreciated. Thanks!

**Comment by Chiagozie-Umeano** [comment]
Having same problem. Please what am I doing wrong? Tried with another version, but still the same problem.

 Trying to install package ‘dplyr’ now...
also installing the dependency ‘rlang’

package ‘rlang’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘rlang’
Warning: restored ‘rlang’
package ‘dplyr’ successfully unpacked and MD5 sums checked

| Could not install package ‘dplyr’!

  |                                                                            
  |                                                                      |   0%Error in seq.default(0, 1, length.out = nrow(e$les)) : 
  argument 'length.out' must be of length 1
In addition: Warning message:
In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Chiagozie\Documents\R\win-library\4.0\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\Chiagozie\Documents\R\win-library\4.0\rlang\libs\x64\rlang.dll: Permission denied

| Leaving swirl now. Type swirl() to resume.

**Comment by dnameispaone** [comment]
I am facing the same problem.

Does anyone have any solution that works?

**Comment by DaphniaDoc** [comment]
I am having a similar problem except that I am getting the following message for the lesson.
| Package ‘dplyr’ loaded correctly!

Error in yaml.load(readLines(con, warn = readLines.warn), error.label = error.label,  : 
  (C:/Users/daniellec/OneDrive - Lacerta Therapeutics, Inc/Documents/R/R-4.1.2/library/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/lesson.yaml) Scanner error: while scanning a tag at line 205, column 9 did not find expected whitespace or line break at line 205, column 19
In addition: Warning message:
`tbl_df()` was deprecated in dplyr 1.0.0.
Please use `tibble::as_tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 

| Leaving swirl now. Type swirl() to resume.

I have uninstalled all courses and reinstalled "Getting and Cleaning Data" and it still displays this message. I have tried to install it from my machine and get the same message so I can only assume there is a problem with the course file itself. 

Can anyone confirm? I am rather new so I would like to check my logic.

**Comment by Schmaef** [comment]
@DaphniaDoc had the same error. 

Just open the file lesson.yaml (e.g. with Notepad++) and go to line 205. There you delete everything and paste:  
> Hint: ""
