### ISSUE TITLE
Swirl Problem installing R programming 

### ISSUE THREAD

**Issue by johnD12** [swirldev/swirl_courses#296]

**Comment by johnD12** [comment]
this is the error I am receiving:

Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/TS56188/Documents/Desktop/swirl_courses-master' cannot be opened

**Comment by johnD12** [comment]
I have tried and look at the other threads but when i tried those they did not work for me

**Comment by seankross** [comment]
Do you own the computer that you're working on?

**Comment by johnD12** [comment]
yes i do and I re-retried the install_course_directory method and that let me in. Thank you. Apologize for the inconvenience
