### ISSUE TITLE
R programming Functions

### ISSUE THREAD

**Issue by Prince-Rana** [swirldev/swirl_courses#297]
Facing the below Error in  **"R programming Functions"**
Also find the attached screenshot, Link :---
https://cloud.githubusercontent.com/assets/17157623/15800373/b65d304c-2a94-11e6-851c-82c2c3bd2fe6.png

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

**Comment by seankross** [comment]
See https://github.com/swirldev/swirl/issues/434#issuecomment-201907367

**Comment by Prince-Rana** [comment]
Thank You @seankross
