### ISSUE TITLE
Error in swirl functions module (c.f  swirl errors out in the Functions module #434 )

### ISSUE THREAD

**Issue by SergeantPluck** [swirldev/swirl_courses#315]
Re this problem: https://github.com/swirldev/swirl/issues/434

Hello the fix worked for this but is there any way to get the instructions to appear in the internal R editor I already have open and not the awkward pop-out window? This was how it used to be. Thanks.

**Comment by seankross** [comment]
This will happen in swirl 2.4.2 which I am submitting to CRAN today 😄
