### ISSUE TITLE
Exit loop in "Grouping and Chaining with dplyr" topic within Getting and Cleaning Data

### ISSUE THREAD

**Issue by VincentJRoy** [swirldev/swirl_courses#317]
ISSUE: The R Script was never created in R Studio and Error in editor(file = file, title = title) :  so it is impossible to continue with swirl....running on console  MS Open R 3..2.5

| Would you like to continue with one of these lessons?

1: Getting and Cleaning Data Grouping and Chaining with dplyr
2: No. Let me start something new.

Selection: 1

| Attempting to load lesson dependencies...

| Package ‘dplyr’ loaded correctly!

| Let's take it a step further.# I just opened an R script for you that contains
| a partially constructed call to summarize(). Follow the instructions in the
| script comments.
| 
| When you are ready to move on, save the script and type submit(), or type
| reset() to reset the script to its original state.

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
See https://github.com/swirldev/swirl/issues/434#issuecomment-201907367
