### ISSUE TITLE
EDA: Exploratory Data Analysis CaseStudy: error 

### ISSUE THREAD

**Issue by SrikumarGopal** [swirldev/swirl_courses#318]
not accepting the correct information in swirl EDA Case study lesson

| Entering the following correct answer for you...
> x1 <- pm1$Sample.Value
| One more time. You can do it! Or, type info() for more options.
| Type x1 <- pm1$Sample.Value at the command prompt.
x1 <- pm1$Sample.Value 
| That's not exactly what I'm looking for. Try again. Or, type info() for more options.
| Type x1 <- pm1$Sample.Value at the command prompt.

how to fix this issue? pls help

**Comment by seankross** [comment]
Have you tried restarting R and swirl?

**Comment by SrikumarGopal** [comment]
thanks Sean. I reinstalled Swirl and the package. it works now.

**Comment by akaEmma** [comment]
I tried restarting R and reloading swirl(). No dice. Here's what's happening:

**Now it's clearer what information each column of pm0 holds. The measurements of
particulate matter (pm25) are in the column named Sample.Value. Assign this component of
pm0 to the variable x0. Use the m$n notation.

> skip()

Entering the following correct answer for you...

> x0 <- pm0$Sample.Value

Nice try, but that's not exactly what I was hoping for. Try again. Or, type info() for
more options.

Type x0 <- pm0$Sample.Value at the command prompt.

>**

**Comment by akaEmma** [comment]
I reinstalled the whole Swirl package and started over. That did it.
