### ISSUE TITLE
Rstudio stop responding after loading  Principles of Analytic Graphs

### ISSUE THREAD

**Issue by AnkitaAwati** [swirldev/swirl_courses#320]
Hello,
I installed "Exploratory Data Analysis" course in R studio Version 0.99.902 with R version 3.3.1.
I am trying to load lesson Principles of Analytic Graphs, and after some lines rstudio stops responding.

I have attached the screenshots.
Please suggest solution.

![error_swirl](https://cloud.githubusercontent.com/assets/17146274/16852453/d6915e0a-4a25-11e6-820c-88d4d29fb304.png)

**Comment by seankross** [comment]
Have you tried clearing your global environment before starting the lesson? You can accomplish this with:

```r
rm(list = ls())
```

**Comment by AnkitaAwati** [comment]
yes I have tried clearing global environment but the same problem occurs.
When I run any course in R programming, I am not getting any problem.
I think problem occurs when any kind of plot comes in swirl. Because I tried loading "Exploratory Graphs" same problem occurs.

**Comment by AnkitaAwati** [comment]
Uninstalled R and R studio, reinstalled it. Still problem occurs. I am unable to access any course in "Exploratory Data Analysis". 
Please suggest solution.

**Comment by seankross** [comment]
What do you get as the result of `sessionInfo()`?

**Comment by AnkitaAwati** [comment]
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
[4] LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1

**Comment by seankross** [comment]
Does plotting work regularly outside of swirl?

**Comment by AnkitaAwati** [comment]
Yes. Please find below attached code and outcome
![plot_](https://cloud.githubusercontent.com/assets/17146274/16884265/185efa3e-4ae6-11e6-8319-364a31a80e1c.png)

**Comment by seankross** [comment]
What do you get as a result of `swirl_options()`?

**Comment by AnkitaAwati** [comment]
> swirl_options()
$swirl_courses_dir
NULL

$swirl_data_dir
NULL

$swirl_language
NULL

$swirl_logging
NULL

**Comment by seankross** [comment]
Have you tried reinstalling the `jpeg` package?

**Comment by AnkitaAwati** [comment]
Yes I had tried installing jpeg package but it didn't worked. I tried on different PC and it worked. Couldn't find out the root cause. As it is working now, so the issue can be closed. Thank you.
