### ISSUE TITLE
Installing R Programming from swirl

### ISSUE THREAD

**Issue by Kiminy** [swirldev/swirl_courses#322]
I have installed package swirl and loaded too. Its running. But when it asks to choose option for installing R programming basic course it says No internet connection. Please I need help to overcome this issue. This is the output.

To begin, you must install a course. I can install a course for you from the
| internet, or I can send you to a web page
| (https://github.com/swirldev/swirl_courses) which will provide course options
| and directions for installing courses yourself. (If you are not connected to
| the internet, type 0 to exit.)

1: R Programming: The basics of programming in R
2: Regression Models: The basics of regression modeling in R
3: Statistical Inference: The basics of statistical inference in R
4: Exploratory Data Analysis: The basics of exploring data in R
5: Don't install anything for me. I'll do it myself.

Selection: 1

| Sorry, but I'm unable to fetch ‘R Programming: The basics of programming in
| R’ right now. Are you sure you have an internet connection? If so, would you
| like to try again or visit the course repository for instructions on how to
| install a course manually? Type 0 to exit.

1: Try again!
2: Send me to the course repository for manual installation.

**Comment by beckyannhughes** [comment]
I am having the same issue. I am getting the following error that says there is no package called "curl" 

> swirl::install_course("R Programming")
Error in loadNamespace(name) : there is no package called ‘curl’

**Comment by beckyannhughes** [comment]
Name of the course and lesson within which you are experiencing the problem: **R Programming**
Brief description of the problem: **See above. The R Programming course will not load**
Any screenshots or output that might help us visualize the problem: 
![image](https://cloud.githubusercontent.com/assets/9167480/17086778/a42058ae-51af-11e6-966e-cc45e2118f49.png)
Your operating system (Windows, Mac, Linux, etc.): **Mac - OS X Yosemite 10.10.5**
The output you get from typing sessionInfo() in the console: **See above**

**Comment by beckyannhughes** [comment]
Final note: I am getting the same error for all courses in the swirl repository. 

Thanks for helping to resolve this!

**Comment by Rebitt** [comment]
Hi Becky!

You can try to install directly with the following code: 
1) install.packages("swirl")
2) library(swirl)
install_from_swirl("Course Name Here")
swirl()

In "Course Name Here" put the name of one of the courses. If you want at firste de R Programing course from Coursera as folowing: install_from_swirl("R Programming")
You can look forward all the indications here: 
https://github.com/swirldev/swirl_courses#swirl-courses

**Comment by beckyannhughes** [comment]
Thanks Rebitt 

I actually tried that a few times but continued getting an error. Since it seems there was a missing package: "curl" I installed that, ran swirl again and now everything is working. 

Here is the command I used to get Swirl to working properly: install.packages("curl")

-Becky Ann

**Comment by Kiminy** [comment]
it is true. you to install curl in order to run smoothly

**Comment by MMarcelo85** [comment]
Runing R 3.5.3 on Linux Mint 19.3 and tryed to isntall R_Programming course Through install_from_swirl() and the program encontered Fatal Error and session was terminated every time until i have installed de curl package. So go for curl library before traying to install a course
