### ISSUE TITLE
Getting & Cleaning Data, swirl Lesson 02: summarize1.R results in error

### ISSUE THREAD

**Issue by jmichaelgilbert** [swirldev/swirl_courses#332]
Hi: In the swirl() course, Getting and Cleaning Data: swirl Lesson 2: Grouping and Chaining with dplyr, I receive an error when submitting the summarize1.R script. The script I'm submitting is identical to [here](https://github.com/swirldev/swirl_courses/blob/master/Getting_and_Cleaning_Data/Grouping_and_Chaining_with_dplyr/scripts/summarize1-correct.R). 

The resulting error is: "Error in n() : This function should not be called directly"

I'm using R version 3.3.1, on Windows 10, with {dplyr} version 0.5.0, and {swirl} version 2.4.2.

Michael

_Edit_: This issue is apparently fixed by typing 'options(editor = "internal")' prior to calling swirl()

**Comment by seankross** [comment]
Try reinstalling the course:

```r
library(swirl) 
uninstall_course("Getting and Cleaning Data")
install_course("Getting and Cleaning Data")
swirlI()
```

Let me know if that works for you.

**Comment by jmichaelgilbert** [comment]
Hi Sean,

Traveling for work through the weekend and don't have access to my main box with R on it. Will let you know as soon as possible, but may not be until Monday.

Michael

**Comment by jmichaelgilbert** [comment]
Hi Sean,

Followed your steps and no longer receive the error. Thanks much for the help and quick reply!

Michael

**Comment by kmarepalli** [comment]
Oh this worked well...Thank You Sean.
