### ISSUE TITLE
Error in summarise_impl(.data, dots) :    attempt to use zero-length variable name while running summarize1.R

### ISSUE THREAD

**Issue by jenherreraj** [swirldev/swirl_courses#335]
Hello, I am running the script summarize1.R and confirmed the script is ok, but when I submit it I got the following error:
| Sourcing your script...

Error in summarise_impl(.data, dots) : 
  attempt to use zero-length variable name

This  is the script:
pack_sum <- summarize(by_package,
                      count = n(),
                      unique = n_distinct(ip_id),
                      countries = n_distinct(country),
                      avg_bytes = mean(size))

Have you had & solved this error before) If so, please helpme, thanks.

**Comment by seankross** [comment]
What course and lesson is this for?

**Comment by jenherreraj** [comment]
IT is the Practice Programming Assignment: swirl Lesson 2: Grouping and Chaining with dplyr of week 3, Getting and Cleaning Data course. Please, could you help? Thanks.

**Comment by seankross** [comment]
Have you tired starting the lesson over again? Make sure your global environment is clear when you start the lesson. If you could send a screenshot of this error when it happens that would help. Also make sure you have the latest version on dplyr.

**Comment by ahbleite** [comment]
Did you save the file prior to submit it?

**Comment by btaha10** [comment]
I am seeing the same issue with summarize1.R. 
Yes I did save the file and reinstalled dplyr, yet the problem still remains
Here is a snapshot of my environment:

![dplyr](https://cloud.githubusercontent.com/assets/22384619/19791551/d3a1ec02-9c76-11e6-9edc-efa12c25719f.JPG)

**Comment by rahamrahimi** [comment]
Save the script file and it will do it.

**Comment by sekR4** [comment]
This helped. Thank you.

**Comment by veonliew** [comment]
Hi Sean, 
What global environment I have to set my working directory to in this case for running the script summarize1.R?  I have tried to save in the default directory in both RStudio and RGui, but it still gave me the same error 
Error in summarise_impl(.data, dots) :
 attempt to use zero-length variable name
Please advise

**Comment by robert-hoyt** [comment]
I am having the same issue as above. Here is the script I created and saved as summarize1.R 
> pack_sum <- summarize(by_package, count = n(), unique = n_distinct(ip_id), countries = n_distinct (country), avg_bytes = mean(size))
> submit()
I did reset() and started over with the same results. This stops me in the swirl course so please help and thanks
