### ISSUE TITLE
Exploratory Data Analysis/ lattice plotting system

### ISSUE THREAD

**Issue by ajaybyan** [swirldev/swirl_courses#338]
I don't know why do I get this error. I cannot proceed forward even if I skip the question.

Again, the values match the plot. That's reassuring. We've copied some code from the slides for
| you. To see it, type myedit("plot1.R"). This will open your editor and display the R code in it.
>  myedit("plot1.R")
 Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default > type myedit("plot1.R")

**Comment by seankross** [comment]
What version of swirl do you have? Also see https://github.com/swirldev/swirl/issues/434#issuecomment-201907367

**Comment by ajaybyan** [comment]
I am using R version 3.1.2 (64 bit) in windows
