### ISSUE TITLE
Error in Swirl Lesson 3 (swirlExpectation)

### ISSUE THREAD

**Issue by FlixMarc** [swirldev/swirl_courses#340]
Hey there,

I have a problem in Swirl level 3 - now matter how I answer the question "What do you think tf will look like" the program leaves swirl with an [error in swirlExpectations (condition(object)) : could not find function "is_equivalent_to"]. Does anyone have the same problem and can help me with that?
Thanks in advance!

**Comment by MiloudEloumri** [comment]
I have the same problem.

**Comment by MiloudEloumri** [comment]
- After Googling a bit, 

- I believe the "is_equivalent_to" is part of [testthat package](http://artax.karlin.mff.cuni.cz/r-help/library/testthat/html/is_equivalent_to.html)

- So, you may need to install it using: install.packages("testthat") 

- **_# But_** it shows problems in the installation of testthat package

- **Also**, if you install the testthat package, **the swirl package will fail**! and you will need to install the swirl package again.

- _If you do install swirl again, you will lose your learning history progress_ stored in your current working directory in .Rhostry or .Rdata file. 

**- So, it might not be the solution you go for.**

**Comment by seankross** [comment]
@MiloudEloumri answer is correct. Thanks.

**Comment by MattJones76** [comment]
Same issue, solution isn't working for me. I'm still receiving the same prompt after installing the testthat package, and reinstalling the swirl package.

`Error in testthat_expectation$passed : 
  $ operator is invalid for atomic vectors

| Leaving swirl now. Type swirl() to resume.`

**Comment by MattJones76** [comment]
Here's a different solution:
https://github.com/swirldev/swirl_courses/issues/339

Worked for me. Thanks.
