### ISSUE TITLE
Data Manipulation Titanic 3 - R Programming Environment - Correct answer not accepted

### ISSUE THREAD

**Issue by Scheenmi** [swirldev/swirl_courses#357]
Hi,  

I have an issue with step_3_Titanic.R: 

My code is: 

```
titanic_3 <- titanic %>% 
  select(Survived, Pclass, Age, Sex) %>%
  filter(!is.na(Age)) %>%
  mutate(agecat = cut(Age, breaks = c(0, 14.99, 50, 150), 
                      include.lowest = TRUE,
                      labels = c("Under 15", "15 to 50", "Over 50")))
```

When submitting this code via submit(), I get a refusal with the usual comments. After posting in the Coursera forum, I consulted Git to see what the correct answer should be (i.e. step_3_titanic-correct.R). 
Turns out, my code is identical to the expected answer: 

```
titanic_3 <- titanic %>% 
  select(Survived, Pclass, Age, Sex) %>%
  filter(!is.na(Age)) %>%
  mutate(agecat = cut(Age, breaks = c(0, 14.99, 50, 150), 
                      include.lowest = TRUE,
                      labels = c("Under 15", "15 to 50", "Over 50")))

```
Even after copy-pasting the github code directly into R, swirl is not accepting the answer. 

![error titanic step 3](https://cloud.githubusercontent.com/assets/11374364/22709509/522038b4-ed7a-11e6-93b8-f0588e807dda.PNG)

What I tried so far:
- copy-pasting code from other coursera users
- copy-pasting github code 
- reset the script, 
- clean my workspace and start lesson from scratch 
- closing R and restart
- uninstall the course and restart
- uninstall swirl and restart 

I am running out of ideas. Help is much appreciated!!

Thanks Michael

**Comment by seankross** [comment]
Hi Michael,

This is what I suggest you do:

1. Close R completely.
2. Re-open R.
3. Start the lesson from the beginning.
4. For each question in the Manipulating Data lesson, make absolutely sure that you are only entering code into the text files that swirl opens up for you. You should only be entering `submit()` into the R console. Do not enter any data manipulation code into the R console.

Let me know whether or not that works.

**Comment by Scheenmi** [comment]
Hi Sean, 

I tried it, but it didn't work:
1. Closed R and all open scripts. Emptied workspace.
2. Re-open R and swirl().
3. Start the lesson from step1.
4. Entered the code into the script and typed submit() directly into the console. No other actions were performed. 

What I noticed is that in all previous steps, R seems to throw an error which does not seem to affect the response validation. Here example for step_2_titanic.R:

```
`> titanic_2 <- titanic %>% 
+   select(Survived, Pclass, Age, Sex) %>%
+   filter(!is.na(Age))
> submit()

| Sourcing your script...

Error in source(e$script_temp_path, encoding = "UTF-8") : 
  C:\Users\kl_sc\AppData\Local\Temp\RtmpkL5vm0/step_2_titanic.R:33:0: unexpected end of input
31: titanic_2 <- titanic %>% 
32:   select(Survived, Pclass, Age, Sex) %>%
   ^

| Great job!`
```

**The only step without error message is step_3_Titanic.R. Could there be a relation?**

**Comment by seankross** [comment]
Hey @Scheenmi,

Looking at your code above:

```
`> titanic_2 <- titanic %>% 
+   select(Survived, Pclass, Age, Sex) %>%
+   filter(!is.na(Age))
> submit()
```

 it looks like you assigned `titanic_2` in the R console. Please don't do that! Like I said before:

> make absolutely sure that you are only entering code into the text files that swirl opens up for you. You should only be entering submit() into the R console. Do not enter any data manipulation code into the R console.

If it's still not working let me know.

**Comment by Scheenmi** [comment]
Sean,


just to be sure there isn't a missunderstanding:


- I alter the text in the scripts opened automatically by R.

- For all steps, I mark the corresponding code and run it by clicking CTRL+ENTER (code is then shown in the concole)

- I then click into the console (not the script), type 'submit()' and ENTER

- Error message occurs


Is this what you mean?


Kr,

Michael



________________________________
Von: Sean Kross <notifications@github.com>
Gesendet: Donnerstag, 16. Februar 2017 20:57
An: swirldev/swirl_courses
Cc: Scheenmi; Mention
Betreff: Re: [swirldev/swirl_courses] Data Manipulation Titanic 3 - R Programming Environment - Correct answer not accepted (#357)


Hey @Scheenmi<https://github.com/Scheenmi>,

Looking at your code above:

`> titanic_2 <- titanic %>%
+   select(Survived, Pclass, Age, Sex) %>%
+   filter(!is.na(Age))
> submit()


it looks like you assigned titanic_2 in the R console. Please don't do that! Like I said before:

make absolutely sure that you are only entering code into the text files that swirl opens up for you. You should only be entering submit() into the R console. Do not enter any data manipulation code into the R console.

If it's still not working let me know.

**Comment by seankross** [comment]
Hi @Scheenmi,

> - I alter the text in the scripts opened automatically by R.

Good!

> - For all steps, I mark the corresponding code and run it by clicking CTRL+ENTER (code is then shown in the console)

Ah no don't do this! Just alter the text, then save the script, then type `submit()` into the console and press ENTER.

Sorry for the confusion.

**Comment by Scheenmi** [comment]
Hi Sean, 

with your explanation it worked. Here a few hints for those who encounter the same issue: 

- Closed R and all open scripts. Empty your workspace.
- Re-open R and swirl().
- Start the Data Manipulation lesson.
- Enter the code into the script. **ATTENTION: just type it in, do NOT run the code (via CTRL+ENTER)**
- Save the script.
- Type 'submit()' directly into the console and hit ENTER.

The problem was that I actually ran the code from the script into the console, and this seems not to work for step_3_Titanic.R. 

Thanks for your support Sean!
Much appreciated!

**Comment by ridenourranchcompany** [comment]
Hi,
 I am doing an R course that uses Swirl.  I am in chapter 12 of the R Programming Environment - Data Manipulation.  I am stuck on the final problem about the Titanic Survivors.  I began with code from the previous question, which creates the first data frame. 

    titanic_4 <- titanic %>% 
      select(Survived, Pclass, Age, Sex) %>%
      filter(!is.na(Age)) 
       mutate(agecat = cut(Age, breaks = c(0, 14.99, 50, 150), 
                      include.lowest = TRUE,
                      labels = c("Under 15", "15 to 50",
                                 "Over 50")))
       head (titanic_4)

     

    # After the previous question, you should have transformed the `titanic`
    # data to look like this:
    #
    ##   Survived Pclass   Age     Sex      agecat
    ##          0      3    22    male    15 to 50
    ##          1      1    38  female    15 to 50
    ##          1      3    26  female    15 to 50
    ##          1      1    35  female    15 to 50
    ##          0      3    35    male    15 to 50
    ##          0      1    54    male     Over 50
    #
    # Add one or more `dplyr` or `tidyr` functions to the pipe chain in 
    # the code at the bottom of the script to change the `titanic` 
    # dataset. The first six lines of the final `titanic_4` dataset 
    # should look like the following example, with the number of
    # passengers, number of survivors, and percent survival stratified
    # by passenger class, age category, and sex. Be sure to use the 
    # same column names as shown in the example output. 
    #
    ## Pclass   agecat    Sex      N     survivors   perc_survived
    ## <int>   <fctr>    <chr>   <int>     <int>         <dbl>
    ##   1    Under 15  female     2         1        50.000000
    ##   1    Under 15    male     3         3       100.000000
    ##   1    15 to 50  female    70        68        97.142857
    ##   1    15 to 50    male    72        32        44.444444
    ##   1    Over 50   female    13        13       100.000000
    ##   1    Over 50     male    26         5        19.230769

To solve this problem, I created this code:

  

    titanic_4 <- titanic %>% 
      select(Survived, Pclass, Age, Sex) %>%
      filter(!is.na(Age)) %>%
      mutate(agecat = cut(Age, breaks = c(0, 14.99, 50, 150), 
   

                           include.lowest = TRUE,
                              labels = c("Under 15", "15 to 50",
                                         "Over 50"))) %>%
          group_by(Pclass,agecat,Sex) %>%
          summarize(N=n(), survivors = sum(Survived))%>%
          mutate(perc_survived = sprintf("%.6f", 
          ((survivors/N)*100.000000)))
    
      head(titanic_4)

Which gives this output:

    # A tibble: 6 x 6
    # Groups:   Pclass, agecat [3]
      Pclass   agecat    Sex     N survivors perc_survived
       <int>   <fctr>  <chr> <int>     <int>         <chr>
    1      1 Under 15 female     2         1     50.000000
    2      1 Under 15   male     3         3    100.000000
    3      1 15 to 50 female    70        68     97.142857
    4      1 15 to 50   male    72        32     44.444444
    5      1  Over 50 female    13        13    100.000000
    6      1  Over 50   male    26         5     19.230769

The above output is wrong because the last column (perc_survived) is a character <chr> instead of a <dbl>.

To solve this, I tell R to change the type to numeric with the as.numeric function.


      titanic_4 <- titanic %>% 
      select(Survived, Pclass, Age, Sex) %>%
      filter(!is.na(Age)) %>%
      mutate(agecat = cut(Age, breaks = c(0, 14.99, 50, 150), 
                          include.lowest = TRUE,
                          labels = c("Under 15", "15 to 50",
                                     "Over 50"))) %>%
      group_by(Pclass,agecat,Sex) %>%
      summarize(N=n(), survivors = sum(Survived))%>%
      mutate(perc_survived = sprintf("%.6f", (perc_survived = as.numeric 
      ((survivors/N)*100.000000))))  
       head(titanic_4)


which creates this output:

    # A tibble: 6 x 6
    # Groups:   Pclass, agecat [3]
      Pclass   agecat    Sex     N survivors perc_survived
       <int>   <fctr>  <chr> <int>     <int>         <dbl>
    1      1 Under 15 female     2         1      50.00000
    2      1 Under 15   male     3         3     100.00000
    3      1 15 to 50 female    70        68      97.14286
    4      1 15 to 50   male    72        32      44.44444
    5      1  Over 50 female    13        13     100.00000
    6      1  Over 50   male    26         5      19.23077

 The new problem is that the output is rounded to 5 digits after the decimal place instead of 6 digits.  I have tried every combination I can find, but have not been able to tell r to keep 6 decimals when it converts from character to numeric.

I'm stuck and need some guidance from a generous person.  Thank you,  Andrew

**Comment by ClaudiusDuPlessis** [comment]
Hi provedup,

Have you solved this problem, I am also having this problem. Also after trying your exact code I still get output as a char not dbl?
