### ISSUE TITLE
getting coursera certifcate for swirl

### ISSUE THREAD

**Issue by gprabhathk** [swirldev/swirl_courses#366]

**Comment by gprabhathk** [comment]
what is the coursera certificate token for swirl course, where do we find them?

**Comment by gprabhathk** [comment]
| Would you like to receive credit for completing this course on Coursera.org?

1: No
2: Yes

Selection: yes
Enter an item from the menu, or 0 to exit
Selection: 2
What is your email address? gprabhathk@gmail.com
What is your assignment token

**Comment by shiv2995** [comment]
You can find it on right side while in the coursera's assignments page . For each assignment you will have a different code.

**Comment by gprabhathk** [comment]
@shiv2995 thanks
