### ISSUE TITLE
unexpected exit - swirl - R programming - module 15 graphics

### ISSUE THREAD

**Issue by field654** [swirldev/swirl_courses#372]
I was learning this module. I made a mistake and the system gave me a bunch of warnings and exited.

I was able to resume the class, but I figured there's maybe a bug in the program. I would like to notify you.

Thanks,
Field
![bug](https://user-images.githubusercontent.com/16052534/29178007-4616688e-7dbe-11e7-8dea-2e522cdc4ef0.jpg)

**Comment by seankross** [comment]
Thanks Field, I'll look into it.
