### ISSUE TITLE
not able to install "Open Intro" or "Data Analysis" Couses

### ISSUE THREAD

**Issue by m4r1usL** [swirldev/swirl_courses#383]
I am unable to install the above mentioned causes ("Exploratory Data Analysis" and "R Programming" worked just fine).
This is what i get... and i Cant seem to find the .swc files.
![screen shot 2017-12-14 at 00 21 30](https://user-images.githubusercontent.com/34525180/33967738-09231e18-e065-11e7-8374-ea2ab8244d36.png)

**Comment by m4r1usL** [comment]
Also the .zip method doesn't work.
![screen shot 2017-12-14 at 00 38 30](https://user-images.githubusercontent.com/34525180/33968223-3bb61554-e067-11e7-96ee-ae894dcdd36b.png)
![screen shot 2017-12-14 at 00 38 54](https://user-images.githubusercontent.com/34525180/33968224-3bd210ba-e067-11e7-9ba6-3668bee9bd7a.png)

**Comment by seankross** [comment]
Both of these courses are no longer supported.

**Comment by m4r1usL** [comment]
Thanks Sean.
Is there another Way to get an overview of statistics from within R, that you could recommend?

all the best
Marius

**Comment by seankross** [comment]
Absolutely, try the Statistical Inference swirl course.

**Comment by m4r1usL** [comment]
Thx Sean. I appreciate your help.
