### ISSUE TITLE
Getting_and_Cleaning_Data/Manipulating Data with dplyr - error : Invalid tag for scalar: int#base60

### ISSUE THREAD

**Issue by ckntav** [swirldev/swirl_courses#389]
Hi, I would like to read the Lesson 1: Manipulating Data with dplyr of the course "Getting and cleaning data"

After installing the course with the following command,
```library(swirl)
install_from_swirl("Getting and Cleaning Data")
swirl()
```

I end up with this error message:
```
| Please choose a lesson, or type 0 to return to course menu.

1: Manipulating Data with dplyr
2: Grouping and Chaining with dplyr
3: Tidying Data with tidyr
4: Dates and Times with lubridate

Selection: 1

| Attempting to load lesson dependencies...

| Package ‘dplyr’ loaded correctly!

Error in yaml.load(readLines(con), error.label = error.label, ...) : 
  (/home/chris/R/x86_64-pc-linux-gnu-library/3.4/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/lesson.yaml) Invalid tag for scalar: int#base60

| Leaving swirl now. Type swirl() to resume.
```

It seems that there is an error with the yaml file or did I do something wrong?
Thanks

EDIT: I just found that other Coursera's students encounter the same issue: https://www.coursera.org/learn/data-cleaning/discussions/weeks/3/threads/Ui0zUx1gEeiyDhJtnKX-OA

**Comment by seankross** [comment]
Try: `install_course("Getting and Cleaning Data")`

**Comment by gebrumulu** [comment]
am getting the same issue too. please help?
![image](https://user-images.githubusercontent.com/37135539/37077883-e3b1dcfa-21aa-11e8-80ea-71ef11c440c7.png)

**Comment by mbaradas** [comment]
@ckntav link to the Coursera comment worked for me.
