### ISSUE TITLE
swirlstats.com down

### ISSUE THREAD

**Issue by CVandiedonck** [swirldev/swirl_courses#467]
Hi,
The site http://www.swirlstats.com/ seems to be down.
I wanted to access to the repository "R programming: The basics of programming in R" for my teaching classes tomorrow.
Is there any hope this issue can be quickly fixed?

Or is there an alternative to install this course from another repository?

Many thanks for your help!

**Comment by seankross** [comment]
Use this for now:
https://web.archive.org/web/20200724234605/https://swirlstats.com/

We are working to get the site back up.

**Comment by CVandiedonck** [comment]
Thanks a lot!
