### ISSUE TITLE
Warning on exiting after selecting "2. Take me to the Swirl course repository"

### ISSUE THREAD

**Issue by hugotoledo** [swirldev/swirl_courses#48]
(Nick, I'd not seen the issues section here. I'll use this to notify you from now on.)

NOTE: this may be solely be due to my locale being "English_United States.1252" rather than "en_US.UTF-8". However, my run through "Lesson 4: Dates and Times with lubridate" didn't throw off any warnings or errors until the second to last question, here:

```
| Now use as.period(how_long) to see how long it's been.

> as.period(how_long)
[1] "6y 3m 11d 21H 24M 55.1787569522858S"
Warning message:
In Ops.factor(left, right) : - not meaningful for factors

| Excellent job!

  |==========<snip>===========================================     |  96%

| This is where things get a little tricky. Because of things like leap years, leap seconds, ...
```

The next (last) question on stopwatch() didn't throw a warning or error.

However, the same warning appears on exiting Swirl, as shown here:

```
1: Getting and Cleaning Data
2: Take me to the swirl course repository!

Selection: 2

| OK. I'm opening the swirl courses web page in your browser.

| Leaving swirl now. Type swirl() to resume.

warning messages from top-level task callback 'mini'
Warning message:
In Ops.factor(left, right) : - not meaningful for factors
```

I recognize this may be a very minor matter but, as its appearence may drive a few dozen (hundred?) extra questions over the next few years, it may be worth your looking into it.

Thanks, as always, for a great tool.

**Comment by ekuns** [comment]
I see the same behavior.  Here is the information you're looking for:

R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.3.3 swirl_2.2.21   

loaded via a namespace (and not attached):
 [1] bitops_1.0-6   digest_0.6.6   httr_0.6.1     memoise_0.2.1  plyr_1.8.1    
 [6] Rcpp_0.11.3    RCurl_1.95-4.5 stringr_0.6.2  testthat_0.9.1 tools_3.1.2   
[11] yaml_2.1.13

**Comment by ekuns** [comment]
It looks to me like this is an issue in lubridate.  I've narrowed it down to a specific line in an internal function.  See lubridate issue https://github.com/hadley/lubridate/issues/243 where the warning being complained about above unexpectedly becomes an error.  That issue happens on the same line of the internal function.  Here we get a warning.  There, an error.

The error occurs in lubridate in `R/coercion.r` in method `.int_to_period` in these lines (where `x` is a lubridate Interval):

```
  start <- as.POSIXlt(x@start)
  end <- as.POSIXlt(start + x@.Data)

  to.per <- as.data.frame(unclass(end)) - 
    as.data.frame(unclass(start))
```

I'm opening an issue with lubridate.

**Comment by ekuns** [comment]
FYI: This is fixed in lubridate in the commit https://github.com/hadley/lubridate/commit/2f139715ddb79a80871b76ffa7c07358a48749ad for issue https://github.com/hadley/lubridate/pull/244 -- on May 23, 2014.  I tested the fix and the warning when calling as.period() goes away with it.  I haven't checked that the warning in swirl when exiting the swirl course also goes away.  (But I assume it will.)

Thus, whenever the next release of lubridate occurs, this issue should go away.
