### ISSUE TITLE
Error in file(con, "r") : invalid 'description' argument when running courses:  MacOsx  10.9.5, R Studio Version 0.98.1049, R version 3.1.1   

### ISSUE THREAD

**Issue by tezosman** [swirldev/swirl_courses#49]
Hi There, 

I am running Version 0.98.1049 and cannot run any coursed installed from swirl.  I am getting the following error.

 Please choose a course, or type 0 to exit swirl.

1: R Programming
2: swirldev-swirl courses-0abced2
3: Vectors
4: Take me to the swirl course repository!

Selection: 3

| Please choose a lesson, or type 0 to return to course menu.

1: customTests.R
2: lesson.yaml

Selection: 2

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

I have tried installing and re-installing, still get the same issue.
I am using R version 3.1.1 

Regards
Tez

**Comment by kstohr** [comment]
I am having the same issue. I tried unstalling the specific courses and reinstalling "R programing" and the courses in question. No love. Other suggestions?

**Comment by WilCrofter** [comment]
Was "R Programming" spelled correctly? The upper case R and P are necessary.
