### ISSUE TITLE
Error when running Manipulating Data with dplyr course

### ISSUE THREAD

**Issue by mharpole** [swirldev/swirl_courses#504]
Hello all, I am receving the folllowing error when trying to run the Manipulating Data with dplyr course on th %5 prompt.

warning messages from top-level task callback 'mini'
Warning message:
`tbl_df()` was deprecated in dplyr 1.0.0.
Please use `tibble::as_tibble()` instead.

**Comment by arindamchoudhury** [comment]
R version 4.1.3 (2022-03-10)

I am having this error:

| Please choose a course, or type 0 to exit swirl.

1: Getting and Cleaning Data
2: R Programming
3: Take me to the swirl course repository!

Selection: 1

| Please choose a lesson, or type 0 to return to course menu.

1: Manipulating Data with dplyr
2: Grouping and Chaining with dplyr
3: Tidying Data with tidyr
4: Dates and Times with lubridate

Selection: 1

| Attempting to load lesson dependencies...

| Package ‘dplyr’ loaded correctly!

Error in yaml.load(readLines(con, warn = readLines.warn), error.label = error.label,  : 
  (/home/arindam/R/x86_64-redhat-linux-gnu-library/4.1/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/lesson.yaml) Scanner error: while scanning a tag at line 205, column 9 did not find expected whitespace or line break at line 205, column 19

| Leaving swirl now. Type swirl() to resume.
