### ISSUE TITLE
Misspelling in Getting and Cleaning Data part 2/4 Grouping and Chaining with dplyr 

### ISSUE THREAD

**Issue by nabiha99** [swirldev/swirl_courses#73]
The word equivalent is misspelled.

 "That's exactly what we've done in this script. The result is equivilent, but the code is much less readable and some of the arguments are far away from the function to which they belong. Again, just try to understand what is going on | here, then submit() when you are ready to see a better solution."

**Comment by seankross** [comment]
Closing this because the appropriate change was made.
