### ISSUE TITLE
Bug with rm() in lesson

### ISSUE THREAD

**Issue by davidkane9** [swirldev/swirl_courses#95]
I keep getting an error when using rm() in a lesson. A small reproducible example follows. Create a lesson yaml that looks like:

- Class: meta
  Course: Bug
  Lesson: Bug
  Author: David Kane
  Type: Standard
  Organization: Williams College
  Version: 0.1.1

- Class: cmd_question
  Output: Assign 9 to x using x <- 9.
  CorrectAnswer: x <- 9
  AnswerTests: omnitest(correctExpr='x <- 9')
  Hint: Type x <- 9 to assign 9 to x.

- Class: cmd_question
  Output: Remove x from the workspace.
  CorrectAnswer: rm("x"")
  AnswerTests: any_of_exprs('rm("x")', 'rm(x)')
  Hint: Type rm("x") to remove x from the workspace.

Using testit(), I get:

> set_lesson("~/Desktop/projects/swirl_courses/Bug/Bug/lesson.yaml")

This lesson is located at C:\Users\dkane\Desktop\projects\swirl_courses\Bug\Bug\lesson.yaml

If the lesson file doesn't open automatically, you can open it now to begin editing...

> testit()

| Course installed successfully!

  |                                                                                   |   0%

| Assign 9 to x using x <- 9.

> x <- 9

| Perseverance, that's the answer.

  |===================================================================================| 100%

| Remove x from the workspace.

> rm(x)

| Perseverance, that's the answer.
Error in get(nm, globalenv()) : object 'x' not found

| Leaving swirl now. Type swirl() to resume.

> 

Any ideas? I *thought* that this was working two weeks ago when I initially sent in a pull request with a new lesson for R Programming. But it does not seem to work now.

**Comment by ncarchedi** [comment]
Seems like @WilCrofter's solution should do the trick. Closing the issue. Feel free to reopen if this is still a problem for anyone.
